### ISSUE TITLE
CPU use

### ISSUE THREAD

**Issue by Bart0o** [GeyserMC/Geyser#1229]
**Describe the bug**
Geyser immediately after startup and forever without players consumes ALL available cores.

**To Reproduce**

Start and go to htop and you will see

**Screenshots / Videos**
![Immagine](https://user-images.githubusercontent.com/36593455/91705905-eb56e000-eb7d-11ea-8562-815cd0ad2211.png)

**Server Version**
BungeeCord

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-2f9ff0c) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)

**Additional Context**
https://pastebin.com/Z3jmyri1

**Comment by DoctorMacc** [comment]
This is definitely different from the scoreboard memory leaks as it only affects CPU usage. Two things I would ask:

1: Try without other plugins.
2: Try connecting to another world. This is likely the issue that there's something specifically in the world that's making Geyser go haywire.

**Comment by Bart0o** [comment]
geyser is in the bungeecord

**Comment by TOWUK** [comment]
its fork bungee -> waterfall -> trawertibe -> flamecord...

**Comment by Bart0o** [comment]
it's waterfall

**Comment by diamond-gold** [comment]
From the java command line, it seems like flamecord is the one taking all the cpu and not geyser?

**Comment by DoctorMacc** [comment]
Yes, I would also ensure that it's not a FlameCord-specific issue and that the CPU usage is a Geyser issue.

**Comment by Bart0o** [comment]
the .jar is called flamecord because I thought the problem was that instead with waterfall nothing has changed. You can see it also fell from the dump -_-

**Comment by Bart0o** [comment]
So once you find that it is a Geyser problem I ask you to fix this problem because I badly need this feature. Thanks again.

**Comment by DoctorMacc** [comment]
The problem is that there's not much we can do with this information. No one else has reported this information, so it's likely something specific to your plugins or setup (since you mention it has nothing to do with the world). Have you verified that this happens with no other plugins installed?

**Comment by Bart0o** [comment]
without plugin nothing changes. The problem is Geyser in bungeecord

**Comment by PQguanfang** [comment]
I'm not sure if everyone has this problem, but this problem has bothered me for a long time. In the old version, everything is normal on my server (although my Geyser server was hosting more than 40 players at that time), but the CPU suddenly rises to 100% sometimes(My server use Intel i7). After the scoreboard improvement PR was merged, the situation became worse. As long as the player enters my Geyser server, the CPU will immediately rise to 50%-75%(Paper 1.16.2 with 20 players, use 3%-5%). If there are more players, it will become 100%.

If this problem does not appear among many of you, then could please give me your Geyser, Java Server Software and plugins. I'am glad to test it.

What's more, when I open debug mode with the latest Geyser, the Team Packet xxx spam still exist.

**Comment by Tim203** [comment]
> What's more, when I open debug mode with the latest Geyser, the Team Packet xxx spam still exist.

That doesn't matter, can you try changing the `scoreboard-packet-threshold` to 3?

**Comment by zimzaza4** [comment]
> 问题在于，我们手头的信息无能为力。我们不知道是什么原因造成的。没有人报告过此信息，因此可能是您的插件或设置特有的（因为您提到它与世界无关）。您是否已验证没有安装其他插件会发生这种情况？

I also had this problem

**Comment by zimzaza4** [comment]
I don't have this problem when I use the Geyser 357

**Comment by zimzaza4** [comment]
This is the problem with versions above 359

**Comment by Tim203** [comment]
Can you try to decrease the `scoreboard-packet-threshold` to 3?

**Comment by zimzaza4** [comment]
> 您可以尝试将减少`scoreboard-packet-threshold`到3吗？

CPU utilization is still 50%

**Comment by Tim203** [comment]
Then it can't be due to scoreboards

**Comment by DoctorMacc** [comment]
Can I get Geyser dumps of everyone having this issue?

**Comment by Bart0o** [comment]
https://pastebin.com/Z3jmyri1

**Comment by DoctorMacc** [comment]
Seems like Geyser uses 100% of one of my twelve virtual cores for me.

**Comment by DoctorMacc** [comment]
A fix is in progress.

**Comment by Bart0o** [comment]
High priority?

**Comment by RednedEpic** [comment]
> High priority?

This has already been fixed.

**Comment by Bart0o** [comment]
It's work in progress :/

**Comment by RednedEpic** [comment]
> It's work in progress :/

It was a work in progress yet, but it no longer is and has been fixed :)

**Comment by Bart0o** [comment]
This problem persists, after a few hours of using the cpu it returned to 400%. Usage is all about geyser (discovered with jvmtop)

**Comment by Bart0o** [comment]
As a result, nothing has been done (or only temporarily). I want to clarify that even without any player the cpu goes up (Ah wait if the cpu is at 400% not even the players are able to enter ...)

**Comment by rtm516** [comment]
This was resolved, are you sure you're on the latest Geyser version?

**Comment by Bart0o** [comment]
#374
This server is running Geyser version 1.1.0 (git-master-4f761c5) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)
You are 1 versions behind
when this bug was already fixed as the last one came out today

**Comment by Comstepr** [comment]
@Bart0o Some information the Geyser team may need:
1) A Geyser dump
2) Your Java server's version (/version)
3) Geyser version (/geyser version)
4) Please update to the latest Geyser version and see if it helps
5) If you are on Linux, try ```taskset --cpu-list <cpu number> java -jar <flags> Geyser.jar``` and see if this helps.
6) If you are using BungeeCord, what is the version?

**Comment by Bart0o** [comment]
1)  https://dump.geysermc.org/AdD219itD0miTyfjyWwWvw3jZFZsfFgG
2) This server is running Tuinity version git-Tuinity-"f663f6e" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
3)  This server is running Geyser version 1.1.0 (git-master-4c58568) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)
4) Done
5) I don't know how to find the pid
6) This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:6496349:370 by md_5

**Comment by DoctorMacc** [comment]
@Bart0o according to the JVMTop website, there is a way to run a CPU profiler. That would be a great way to determine what is actually causing the CPU usage.

**Comment by Comstepr** [comment]
As this is still in progress, I suggest this issue is reopened.

**Comment by RednedEpic** [comment]
We’re going to need more detailed information about what is causing the CPU to go so high. So far none of us have been able to reproduce this, but if OP (or anyone really) can provide a CPU profiling report that shows what is causing this issue, please attach it to this issue and we’ll reopen it if we determine it be a Geyser problem.
