### ISSUE TITLE
Enchantment Tables Are Not Working On Bedrock But On Java They Do

### ISSUE THREAD

**Issue by InjuredInflame** [GeyserMC/Geyser#1302]
**Describe the bug**

When I go to enchant an item on bedrock it does not allow me to select a book but for java enchanting

 works fine

**To Reproduce**

**Expected behavior**

went to enchant an item in bedrock to see if it had any problems and it does not allow me to select an enchantment book

**Screenshots / Videos**

![Capture](https://user-images.githubusercontent.com/71354464/93270042-7682c900-f76d-11ea-954f-22c10160c045.PNG)
![2020-09-15_16 14 47](https://user-images.githubusercontent.com/71354464/93270560-a2527e80-f76e-11ea-9203-3e499ddc80a2.png)
![2020-09-15_16 14 52](https://user-images.githubusercontent.com/71354464/93270561-a383ab80-f76e-11ea-9f8f-9b06c0536e39.png)

**Server Version**

Spigot Paper Version 1.16.3-RO.1-SNAPSHOT
running 28 gigs of ddr4 3200mhz ram
ryzen 5 3600 6 core 12 thread processor 

**Geyser Version**

Geyser Version 1.1.0 (git-master-46c3484) (java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**

Bedrock: 1.16.0 - 1.16.100

**Additional Context**

**Comment by DoctorMacc** [comment]
Could you please attach a Geyser dump?

**Comment by DoctorMacc** [comment]
And also please state which Bedrock platform you're playing on.

**Comment by DoctorMacc** [comment]
Confirmed in survival. I have no idea how this one happened.

**Comment by DoctorMacc** [comment]
Nevermind, I forgot about XP.

**Comment by soshimee** [comment]
The screenshot looks fine?

**Comment by InjuredInflame** [comment]
sorry guys wasnt home for the last little bit, when i open an enchantment table on bedrock windows 10 edition it does not allow me to select any book to enchant with on the enchantment table i will atttach a dump shortly as i updated guyser and paper again in the time before i saw this reply

**Comment by DoctorMacc** [comment]
Do you have enough experience to get the enchantment?

**Comment by InjuredInflame** [comment]
Geyser Version 1.1.0 (git-master-99e72f3) (java: 1.16.3, Bedrock:1.16.0-1.16.20)
Paper Version git-paper-197 (mc:1.16.3) Implementing API version 1.16.3-r0.1-SNAPSHOT)
I Tested it in this version and it worked for adding experience and testing on windows 10 bedrock edition possibly a bug with the older version i had been using when first reporting the bug, when testing previously the character had 30 lvls of experence, lapis and an item in all required areas and it would not let me select any enchantment,

Timings Attached with plugin list because i am unsure of what other thing could possibly cause it  as I Dont Think There are anything interferingwith it 
https://timings.aikar.co/?id=e5ceeb9738f34644a6d634abbcb2337e
geyser dump is attached too
https://dump.geysermc.org/48ebB17pzbJkSM9rumH5jwrlRbkcJH2W

**Comment by DoctorMacc** [comment]
Is this issue now resolved, then?

**Comment by DoctorMacc** [comment]
As I've gotten no response for a month, I am going to assume the issue is fixed.

**Comment by Peng1029** [comment]
no this is still a problem i tried this and with 72 levels could not enchant
