### ISSUE TITLE
Can't climb ladders

### ISSUE THREAD

**Issue by PappoYT** [GeyserMC/Geyser#1587]
I cannot climb ladders.
When I try, I will automaticaly get back to the start position.
You can see this issue in this video: [https://youtu.be/9kz3OMnXNqM](https://youtu.be/9kz3OMnXNqM)
I thought (maybe wrongly) that this issue should be solved by pull request #699.

_Server version_: Paper version git-Paper-274 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
_Geyser version_: Build #495 (24 nov 2020, 07:48:32)
_Bedrock Edition version_: 1.16.100

**Comment by Hellohi3654** [comment]
Make sure that cache-chunks is true in the config and make sure that it isn't a anticheat plugin if that server has one

**Comment by PappoYT** [comment]
Thank you @Hellohi3654 for fast reply.

I use this anticheat plugin: antiWitherAC_0.22.1 ([link](https://www.spigotmc.org/resources/wither-anti-cheat-1-13-x-1-16-x-paper-tuinity-support-free-accurate-optimized-anti-cheat.68657/)).

I made a test booting server anticheat: in this case the issue disappear and I am able to climb ladders.
**This means that the problem is anticheat plugin and not Geyser.**

Before close this post I have then some questions:
1) Is there an anticheat plugin that is compatible with Geyser?
2) Or, does install an anticheat plugin make sense or it check only java clients and not bedrock clients?
3) Do I need to set cache-chunks to true anyway?

Thks

**Comment by kobenetwork** [comment]
> Thank you @Hellohi3654 for fast reply.
> 
> I use this anticheat plugin: antiWitherAC_0.22.1 ([link](https://www.spigotmc.org/resources/wither-anti-cheat-1-13-x-1-16-x-paper-tuinity-support-free-accurate-optimized-anti-cheat.68657/)).
> 
> I made a test booting server anticheat: in this case the issue disappear and I am able to climb ladders.
> **This means that the problem is anticheat plugin and not Geyser.**
> 
> Before close this post I have then some questions:
> 
> 1. Is there an anticheat plugin that is compatible with Geyser?
> 2. Or, does install an anticheat plugin make sense or it check only java clients and not bedrock clients?
> 3. Do I need to set cache-chunks to true anyway?
> 
> Thks

Indeed, anti cheats are a problem when using geyser. You can fix this by using bedrock player manager plugin, this way you can give bedrock player a bypass on the anti cheat. Some A-C plugins are 'compatible' but still ain't a good solution.

**Comment by PappoYT** [comment]
Thank You @kobenetwork 
What about Q3: Do I need to set cache-chunks to true anyway?

**Comment by kobenetwork** [comment]
> Thank You @kobenetwork 
> 
> What about Q3: Do I need to set cache-chunks to true anyway?

It's recommended, so yes.

**Comment by PappoYT** [comment]
Thank you man.
I set cache-chunks to true (it was false).

**Comment by Hellohi3654** [comment]
If cache chunks was false then that was the problem not the Anticheat

**Comment by Hellohi3654** [comment]
Also next time you create a issue please include a geyser dump
That way I could of instantly told you the issue

**Comment by PappoYT** [comment]
Thank You @Hellohi3654 

Please consider one thing: when I first removed the anticheat from server the issue immediatly disappear.

Only after I set cache chunks to true. But the problem was already solved.

To be more specific:
- shutdown server
- restart without anticheat
- test: no problem found
- shutdown server
- set cache chunks true
- restart without anticheat
- test: still no problem found

From my point of view it seems anticheat is the problem.

**Comment by Hellohi3654** [comment]
Ok I see
I would recommend using bedrockplayermanager or something similar to allow bedrock players to bypass the Anticheat so then you could still have a Anticheat plugin 
I believe witherAC has perms to bypass certain modules
