### ISSUE TITLE
Collecting Timeout Dumps

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser#1729]
Recently, we've been getting enough cases where people (whether all players or some players) will randomly time out from a Geyser server.

If you believe you are affected by this, please put the following information down below:

- A Geyser dump
- The platforms that people time out on (e.g. Windows 10, Switch, Xbox One...)
- All players or just some?
- If known, what CPU is running Geyser?
- Does lowering the MTU value in your Geyser config do anything? (In increments of 100)

**Comment by TheMattVid** [comment]
https://mclo.gs/UFBhA6k
https://dump.geysermc.org/jdDi9H21GrYoFgzXu11YEX6JmoJ14jjy
Windows 10
Some players affected
CPU: i9-9900k

In the provided logs, player *FluffyDolphin07 is logging into the server for the first time in 18 days. According to his report, he was kicked from the server with a Timed Out message within the first minute he tried to join. Each subsequent time he attempted to join, he did not receive the Timed Out message. Instead, his Windows 10 Edition game crashed entirely. He attempted to join again later in the day (after the daily restart had occurred), but the problem from earlier still persisted.

**Comment by Griffin2020** [comment]
https://spark.lucko.me/#YVD9SSylCb
Platforms: Switch, android
Most players
CPU: Xeon X5672

**Comment by TheMattVid** [comment]
One player on Windows 10 Edition reported that the crashing occurs frequently when at spawn or other major warps. In other words, places where many blocks might be placed or other players might currently be hanging around. The crashing might be related to loading in a large amount of blocks for chunks that have tall builds.

**Comment by Camotoy** [comment]
@TheMattVid can you try uncommenting the `mtu` config option and lowering it? We recommend lowering it by 100 each time.

**Comment by TheMattVid** [comment]
@Camotoy Will do. It was already uncommented and set to 1000 for some reason, but I can continue lowering it by 100 after each restart if I determine that the problem isn't fixed.

Additionally, the timing out for many Bedrock players and crashing among Windows 10 players might be separate issues. Yesterday, when I tested setting my proxy to 2gb rather than 1gb, it seemed that Bedrock players were timing out much less frequently, but I did not test it long enough to be confident in that correlation. I'll continue to keep you updated with what I find.

**Comment by AllforHim0064** [comment]
https://mclo.gs/aEHjs7A
https://dump.geysermc.org/BMyNDkfZV6Pc6sO3Zu4mvLmQSU6RxjXL
I time out whenever I connect to the server from wan it works fine when connecting via lan though. I am able to join the world but none of the chunks load in and I am timed out after about 20 seconds. decreasing MTU did nothing.

**Comment by TheMattVid** [comment]
I have not had the chance to test mtu or increasing memory yet, but I do have new information:

The issue seems to correlate with the number of players online. Two players that have been reporting issues were stable and playing just fine when the player count was around 8. Then, when the player count when up to about 17, their clients would crash (not time out, but actually crash the game) and they would have to reopen the entire game. They would only be able to hang out on the server for about 30 seconds until the next crash. That's why I suspect that resource limitations are causing the issues. Perhaps the laggy proxy is causing some sort of inconsistency with how the packets are being sent to the Bedrock clients in such a way that it confuses the clients. I am hoping that reallocating my proxy from 1gb to 2gb will solve the problem.

**Comment by TheMattVid** [comment]
I have another update. The crashing still occurs with my allocated memory upped to 2gb. I have confirmation from my host that the resources are not maxed out, but yet the crashing still occurs. I take back what I said earlier about it correlating with the number of players online.

What I did find out is that for one of the players experiencing the crashes, Minecraft Windows 10 Edition is taking up about 2/3 of his computer's CPU and his CPU usage is at 100%. I think this might be the cause of the crashes. However, I am not sure if this high CPU is a bug with the game or a problem with the server. Apparently the his computer's CPU usage is slightly lower when he plays on other servers.

**Comment by Camotoy** [comment]
Do you use a scoreboard or a plugin like TAB?

**Comment by TheMattVid** [comment]
I use TAB for the tab list, but I don't have any sort of scoreboard enabled. I don't know if the tab list technically counts as a scoreboard.

**Comment by Camotoy** [comment]
I think it might. Try temporarily removing that and seeing if there is a difference?

**Comment by TheMattVid** [comment]
Yea, it's worth a shot.

**Comment by TheMattVid** [comment]
It seems that completely fixed the crashing. I'm not sure why, but now Bedrock's player list shows more connections than there are players online. There are only 6 players on the server, but this is what they all see:
![image](https://user-images.githubusercontent.com/10250080/103253092-bbfa8900-494d-11eb-874f-8fb33dde1765.png)

**Comment by Camotoy** [comment]
That is when there are other entries in the tab list that are not players. Bedrock doesn't handle that too well at this time. :P

**Comment by TheMattVid** [comment]
What sort of entries might those be?

**Comment by Camotoy** [comment]
Anything that isn't a genuine player, basically.

**Comment by TheMattVid** [comment]
The Java player list only has genuine players, though, as I currently have all tab plugins disabled.

**Comment by Camotoy** [comment]
Oh. Then the plot thickens. 

Any NPCs?

**Comment by TheMattVid** [comment]
No NPC plugins on the server

**Comment by TheMattVid** [comment]
Also, I unfortunately just had another crash from one of the Bedrock players. Not sure if it is more stable than before, or if that is just because I recently restarted.

**Comment by dbwrush** [comment]
Geyser Dump: https://dump.geysermc.org/XAyxkXp68LIBGz552fFCMFbU1Asm6N4w

Platforms: Majority of my Bedrock players are on Windows 10. After them, we have a lot of smartphone/tablet users. We also have 2 Nintendo Switch players, 1 Xbox One and 1 PS4.

All or some: Every Bedrock player I've asked has experienced this at some point. They did tell me that when I added 2 additional CPU cores to the server that they noticed an improvement, but it didn't last.

CPU: I know its Intel Xeon, and that we have 24 cores currently allocated to our VM. That's all I know.

I haven't tried tinkering with the MTU value before, but I'll give it a try. I currently have it set to 1400. I'll try 1300.

If you have any additional questions, I'm happy to help!

**Comment by TheMattVid** [comment]
New update from me. I lowered the mtu to 900. It seems to me much more stable for a few players, but another player is still consistently crashing and timing out after a few seconds.

Because my server is a network, with Geyser on the Bungeecord instance, I suggested to this player to play on my other server. On this other server, there was absolutely no crashing or timing out. I even have TAB still enabled on the other server, but yet, no issues. This indicates to me that something specific to a plugin on survival is likely the cause of the problems for Bedrock players. Perhaps McMMO? I will see if I can diagnose the specific plugin through trial and error.

**Comment by Camotoy** [comment]
Awesome, thank you.

**Comment by mooinglemur** [comment]
On my server (Geyser-Spigot, Floodgate) this seems to show up when there are more than 5 players joined.  MTU is currently set to default.  As soon as the 6th person joins, all of the Geyser players start experiencing timeouts, and at least in my testing on both Switch and Android, chunks will stop loading for those players moving toward the boundaries of what they had loaded, but mobs are still moving.  UDP packets flow in both directions at least all they way up to the timeout message on the client.

[19:49:42] [Server thread/INFO]: This server is running Geyser version 1.2.0-SNAPSHOT (git-master-d1c571d) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)
[19:50:12] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Camotoy** [comment]
Please provide a Geyser dump (`/geyser dump`) and your CPU model.

**Comment by mooinglemur** [comment]
https://dump.geysermc.org/YSp9ZfRXqKCGSuJDzm5mdWSdHHZR9pPU

In the VM, it looks like: Intel Xeon E312xx (Sandy Bridge)
But it's currently running on a Xeon Silver 4114 host.

**Comment by mooinglemur** [comment]
@Camotoy would it be helpful to provide a full tcpdump of this happening?

**Comment by Camotoy** [comment]
If you don't mind, sure. Part of the problem with managing these timeout issues (for me) is that, if they're not protocol related, I'm stumped. I know nothing about networks after the deserialized packet level. That being said, perhaps such a dump will help some other passersby understand the issue.

**Comment by mooinglemur** [comment]
My (only partially-educated) hunch is that the client is encountering some sort of state issue (perhaps it's a client bug that never gets triggered on vanilla Bedrock servers), but where its timeout clock is somehow not getting reset because of some particular order of events/packets from Geyser, but it's even more of a mystery now that it's turning out to be quite a Heisenbug. On my server, we could reliably get Bedrock timeouts with 6 total players even if just one of them was bedrock, but during the packet capture, we've had 8 players on with 1-3 bedrock players and no timeouts.

Just spitballing here to try to inspire leads since I don't know what else I can do to try to trigger the issue.

**Comment by Camotoy** [comment]
For anyone affected by timeout issues, please try https://github.com/GeyserMC/Geyser/pull/1775 . For how to download it:

> To download a pull request (or a "PR") you need to:
1. Make sure you are signed in with a GitHub account
2. Follow that pull request link
3. Follow the guide on this picture
https://ibb.co/pXZ2kbj

**Comment by mooinglemur** [comment]
I'm waiting for my server to become more idle to restart to try running your test build, but in the meantime I got a packet capture of a mobile bedrock client connecting and experiencing a timeout with the version mentioned in https://github.com/GeyserMC/Geyser/issues/1729#issuecomment-752739570  

The capture can be viewed in Wireshark.

https://mooinglemur.com/tmp/20210101-20a.cap.gz

**Comment by Dawn-Shalve** [comment]
My bedrock players are getting timed out.
All bedrock players are getting timed out
https://dump.geysermc.org/ykuLcgQeoXOY5c7Q4KHlskf4uz5Yl8df
All players
A raspberry pi(CPU)
Idk what a MTU is

**Comment by mooinglemur** [comment]
The build linked at https://github.com/GeyserMC/Geyser/issues/1729#issuecomment-753347924 seems to be better, but not perfect. Bedrock players can stay connected longer and more often when there are more players connected as opposed to how it was before the update. I'd say optimistic but inconclusive.

**Comment by Camotoy** [comment]
Better is good, but ideally the problem should be solved entirely. I'll get in touch with whoever I can to try to resolve this entirely.

**Comment by TheMattVid** [comment]
I have not downloaded the new build because I think my problem is solved entirely. With my mtu at 900 and tab plugin removed, none of my Bedrock players seem to be timing out or crashing any longer.

**Comment by mooinglemur** [comment]
> Better is good, but ideally the problem should be solved entirely. I'll get in touch with whoever I can to try to resolve this entirely.

900 MTU helped even more but timeouts still happened occasionally when the server got busy, switching from Spigot to Paper has so far has eliminated the timeouts, but we have a sample size of 12 hours.  It does look promising though.  On Paper but still 900 MTU.

**Comment by Camotoy** [comment]
It appears that this issue is resolved. If it comes back, I will make another thread. Happy Minecrafting!
