### ISSUE TITLE
Using ViaVersion causes Chunk loading error

### ISSUE THREAD

**Issue by linmiao233** [GeyserMC/Geyser#186]
**Describe the bug**
ViaVersion+1.8.8 Chunk loading error,This is not an issue with older versions of Geyser

**To Reproduce**
1.Server version is 1.8.8 using ViaVersion
2. Enter the server and see the error
3. Seeing errors when placing blocks
**Expected behavior**
You should see the block

**Screenshots**
![image](https://s2.ax1x.com/2020/02/27/3d75SH.jpg?raw=true)
![image](https://s2.ax1x.com/2020/02/27/3dHpXn.jpg?raw=true)

**Server version**
1.8.8-1.14+ViaVersion

**Geyser version**
Jenkins latest.

**Bedrock version**
1.14.30

**Comment by linmiao233** [comment]
Older versions of Geyser using 1.8.8 + ViaVersion are perfectly fine.Fully normal in the latest 1.15.2 without iaVersion

**Comment by devil38** [comment]
It seem more delayed chunks refresh rate

**Comment by linmiao233** [comment]
> It seem more delayed chunk refresh rate
Yes, actually the chunk is already loaded, which means that the player cannot see

**Comment by linmiao233** [comment]
> It seem more delayed chunk refresh rate

Yes, actually the chunk is already loaded, which means that the player cannot see

**Comment by LegacyGamerHD** [comment]
update your server issue solved

**Comment by devil38** [comment]
> update your server issue solved

Same issue with 1.12.2

**Comment by RednedEpic** [comment]
> > update your server issue solved
> 
> Same issue with 1.12.2

Unable to reproduce. Can join 1.12 servers using ViaVersion without issues.

**Comment by awgybop1** [comment]
Same issue, doesn't always happen and re-joining the server often fixes it.
The blocks are actually loaded, as you can see their outlines and you don't fall into a void, but there is no texture.

**Comment by LegacyGamerHD** [comment]
thats fixed in latest build

**Comment by LegacyGamerHD** [comment]
> > update your server issue solved
> 
> Same issue with 1.12.2

1.15.2 ....

**Comment by linmiao233** [comment]
> Same issue, doesn't always happen and re-joining the server often fixes it.
> The blocks are actually loaded, as you can see their outlines and you don't fall into a void, but there is no texture.

1.8.8 Tried, it always happens, rejoining the server still can't be solved

**Comment by linmiao233** [comment]
> > > update your server issue solved
> > 
> > 
> > Same issue with 1.12.2
> 
> Unable to reproduce. Can join 1.12 servers using ViaVersion without issues. Can’t say the same for 1.8.8 though as I have had no reason to test with such an old version, but I’ll look into that later

Tested 1.12.2 is still the problem
![QQ图片20200229155741](https://user-images.githubusercontent.com/49273456/75603754-8b1ead00-5b0c-11ea-8b9e-70eae84fccc6.jpg)

**Comment by LegacyGamerHD** [comment]
> > > > update your server issue solved
> > > 
> > > 
> > > Same issue with 1.12.2
> > 
> > 
> > Unable to reproduce. Can join 1.12 servers using ViaVersion without issues. Can’t say the same for 1.8.8 though as I have had no reason to test with such an old version, but I’ll look into that later
> 
> Tested 1.12.2 is still the problem
> ![QQ图片20200229155741](https://user-images.githubusercontent.com/49273456/75603754-8b1ead00-5b0c-11ea-8b9e-70eae84fccc6.jpg)

Not latest update to 1.15.2

**Comment by LegacyGamerHD** [comment]
Paper spigot to be exact

**Comment by linmiao233** [comment]
> > > > > update your server issue solved
> > > > 
> > > > 
> > > > Same issue with 1.12.2
> > > 
> > > 
> > > Unable to reproduce. Can join 1.12 servers using ViaVersion without issues. Can’t say the same for 1.8.8 though as I have had no reason to test with such an old version, but I’ll look into that later
> > 
> > 
> > Tested 1.12.2 is still the problem
> > ![QQ图片20200229155741](https://user-images.githubusercontent.com/49273456/75603754-8b1ead00-5b0c-11ea-8b9e-70eae84fccc6.jpg)
> 
> Not latest update to 1.15.2

I used ViaVersion but Redned said that it was completely normal in 1.12.2 + ViaVersion but my test is still the problem

**Comment by linmiao233** [comment]
> > > > > update your server issue solved
> > > > 
> > > > 
> > > > Same issue with 1.12.2
> > > 
> > > 
> > > Unable to reproduce. Can join 1.12 servers using ViaVersion without issues. Can’t say the same for 1.8.8 though as I have had no reason to test with such an old version, but I’ll look into that later
> > 
> > 
> > Tested 1.12.2 is still the problem
> > ![QQ图片20200229155741](https://user-images.githubusercontent.com/49273456/75603754-8b1ead00-5b0c-11ea-8b9e-70eae84fccc6.jpg)
> 
> Not latest update to 1.15.2

I use ViaVersion just to be compatible with more plugins for the server, and Geyser in the old version is completely normal

**Comment by RednedEpic** [comment]
Unable to reproduce. ![](https://i.imgur.com/lVSP4uo.png)

**Comment by awgybop1** [comment]
Problem is not happening on vanilla Spigot 1.8.8 from what I've seen. Seems to be an issue with Paper Spigot. 
null

**Comment by AJ-Ferguson** [comment]
Try this @linmiao233
[Geyser.zip](https://github.com/GeyserMC/Geyser/files/4270894/Geyser.zip)

**Comment by devil38** [comment]
> Try this @linmiao233
> [Geyser.zip](https://github.com/GeyserMC/Geyser/files/4270894/Geyser.zip)

It work on 1.12.2

**Comment by linmiao233** [comment]
> Unable to reproduce. ![](https://camo.githubusercontent.com/9bb063d25e50d354c466fc8369eeabf89b45c8c2/68747470733a2f2f692e696d6775722e636f6d2f6c56535034756f2e706e67)

Which version of ViaVersion are you using?But no matter which version I try, it is still the problem

**Comment by RednedEpic** [comment]
> Which version of ViaVersion are you using?But no matter which version I try, it is still the problem

Latest on Spigot atm.

**Comment by linmiao233** [comment]
> Latest on Spigot

what do you mean? Latest Spigot 1.15.2 is without this problem

**Comment by linmiao233** [comment]
> > Which version of ViaVersion are you using?But no matter which version I try, it is still the problem
> 
> Latest on Spigot atm.

Sorry for not understanding what you mean? Latest Spigot 1.15.2 is without this problem

**Comment by RednedEpic** [comment]
> Sorry for not understanding what you mean? Latest Spigot 1.15.2 is without this problem

I was testing with the latest available version of ViaVersion on Spigot 1.8.8.

**Comment by linmiao233** [comment]
> Try this @linmiao233
> [Geyser.zip](https://github.com/GeyserMC/Geyser/files/4270894/Geyser.zip)

This is perfectly normal

**Comment by linmiao233** [comment]
> > Sorry for not understanding what you mean? Latest Spigot 1.15.2 is without this problem
> 
> I was testing with the latest available version of ViaVersion on Spigot 1.8.8.

The latest # 180 in JenKins will no longer appear invisible Chunk, but if you place / destroy blocks you will not be able to see him
![8](https://user-images.githubusercontent.com/49273456/75617890-3167c280-5ba0-11ea-8d41-9f541aee8eb1.jpg)
![9](https://user-images.githubusercontent.com/49273456/75617893-388ed080-5ba0-11ea-8afa-3cad5d0d770f.jpg)

**Comment by linmiao233** [comment]
> > Try this @linmiao233
> > [Geyser.zip](https://github.com/GeyserMC/Geyser/files/4270894/Geyser.zip)
> 
> It work on 1.12.2

1.8.8 also works

**Comment by AnonAlpha** [comment]
Spigot 1.15 also have this problem, but it doesn't always happen. Which means it has a possiblity of happening. Also no error log in the console

**Comment by LegacyGamerHD** [comment]
well then your not on latest geyser it hase been fix

**Comment by LegacyGamerHD** [comment]
do it can be just a unknow entity or someting else conflics it

**Comment by AnonAlpha** [comment]
> do it can be just a unknow entity or someting else conflics it

Nope sometimes entities can load but you can't see the blocks, sometimes nothing is loading
And There'a also a possibility that another chunk can load but not the one you are standing in

**Comment by linmiao233** [comment]
@RednedEpic The same problem even entering hypixel
![hyp](https://user-images.githubusercontent.com/49273456/75678153-eea10a00-5cc7-11ea-8cac-8ca313f7c978.jpg)

**Comment by LegacyGamerHD** [comment]
@linmiao233 can i have real time proof your using 1.14.30 because if your not thats why  i player of my got same issue but dident hafe right version try to install the playstore version not chinese edition etc

**Comment by linmiao233** [comment]
> @linmiao233 can i have real time proof your using 1.14.30 because if your not thats why i player of my got same issue but dident hafe right version try to install the playstore version not chinese edition etc

Sorry I'm Chinese, my phone is iphone, what should I do?

**Comment by alissonlauffer** [comment]
> @RednedEpic The same problem even entering hypixel
> ![hyp](https://user-images.githubusercontent.com/49273456/75678153-eea10a00-5cc7-11ea-8cac-8ca313f7c978.jpg)

Cannot reproduce here (I'm using latest Geyser version and Minecraft 1.14.30).
![Screenshot_20200302-104902_Minecraft](https://user-images.githubusercontent.com/29029632/75682052-86c0d400-5c73-11ea-8833-3db2a14333c5.png)

**Comment by alissonlauffer** [comment]
Block placing/breaking is working fine for me also.

**Comment by RednedEpic** [comment]
> @RednedEpic The same problem even entering hypixel
> ![hyp](https://user-images.githubusercontent.com/49273456/75678153-eea10a00-5cc7-11ea-8cac-8ca313f7c978.jpg)

 Could this be due to high ping?

**Comment by linmiao233** [comment]
> > @RednedEpic The same problem even entering hypixel
> > ![hyp](https://user-images.githubusercontent.com/49273456/75678153-eea10a00-5cc7-11ea-8cac-8ca313f7c978.jpg)
> 
> Could this be due to high ping?

I am trying to reinstall minecraft may also be my problem

**Comment by linmiao233** [comment]
It still has no effect. Try again in hypixel, but sometimes the invisible Chunk will appear. Playable in @AJ-Ferguson https://github.com/GeyserMC/Geyser/issues/186#issuecomment-592988641

**Comment by linmiao233** [comment]
I tried again. If you die / re-enter the world, the blocks you placed / destroyed before will be normal. But if you are placing / destroying blocks, it still cannot be displayed.

**Comment by AwesomestCode** [comment]
Confirmed for bungeecord (1.15-SNAPSHOT) to 1.12.2 spigot server running viaversion 2.2.3. GeyserMC is running on the bungee with Floodgate.

**Comment by RednedEpic** [comment]
Superseded by #265.

**Comment by Ruymanphone** [comment]
Can you offer us the previous version of the plugin? It only failed me in this build xd
