### ISSUE TITLE
Player can't move correctly when cord number is higher than 4096 / Slab and stair issues

### ISSUE THREAD

**Issue by SinonGame** [GeyserMC/Geyser#204]
**Describe the bug**
Players get dragged back by server when walking near a wall or getting out of water

**To Reproduce**
1. Use the newest inventory branch
2. build a wall two block(or higher) high
3. Walk near it

**Expected behavior**
Players can walk normally

**Screenshots**
See attached video file
video 1 and 2 for walking near wall
video 3 for getting out of water

**Server version**
spigot 1.15.2 latest build
**Geyser version**
Latest inventory branch

**Bedrock version**
Latest

**Additional context**
[video1](https://discordapp.com/channels/613163671870242838/613168464634576897/686762472522514515)
[video2](https://discordapp.com/channels/613163671870242838/613168464634576897/686762486401466388)
[video3:](https://discordapp.com/channels/613163671870242838/613168464634576897/686767428394287104)

**Comment by RednedEpic** [comment]
This also happens on snow too, just noting this here.

**Comment by AnonAlpha** [comment]
This is the log I got when players are dragged back
`
>.... [08:21:52 WARN]: FairCanying7906 moved too quickly! -163.00652857493054,7.099998474121094,7.462842663621842
>.... [08:21:52 WARN]: FairCanying7906 moved too quickly! -163.00652857493054,7.099998474121094,7.462842663621842
>.... [08:21:52 WARN]: FairCanying7906 moved too quickly! -72.44732857493057,3.5,3.3168426636218555
>.... [08:21:52 WARN]: FairCanying7906 moved too quickly! -48.29822857493053,2.5,2.211242663621846
>.... [08:22:01 INFO]: [Geyser-Bukkit] Spawned player at 361.23611370219476 100.0 -196.3757875449823
>.... [08:22:06 WARN]: FairCanying7906 moved too quickly! -1.8785285749305558,-139.0,0.2442426636218613
>.... [08:22:06 WARN]: FairCanying7906 moved too quickly! -1.2523285749305728,-92.5,0.16284266362185917
>.... [08:22:06 WARN]: FairCanying7906 moved too quickly! -0.6262285749305647,-46.0,0.08144266362185704`
I think this have something to do with #209

**Comment by AnonAlpha** [comment]
It seems that this problem is partly caused by Spigot's anti-cheat which is the
```
moved-wrongly-threshold: 0.0625
moved-too-quickly-multiplier: 100.0
```
in the spigot.yml when tested on changing these numbers very high, the possiblity of player being dragged back decreased(Still happens).

**Comment by RednedEpic** [comment]
I did some testing on a Paper server with no plugins at all and all the default values in a config and was unable to reproduce this. Was able to get out of water just fine and walk on top of repeaters/redstone without and sort of rubberbanding at all. Walked near walls too and was just fine. Even through in a mix of stairs and slabs just for the fun of it and still had no movement problems at all. 

Most likely this is due to an anticheat. Could you please test this without one and report back here with the results? Thanks.

**Comment by AnonAlpha** [comment]
> I did some testing on a Paper server with no plugins at all and all the default values in a config and was unable to reproduce this. Was able to get out of water just fine and walk on top of repeaters/redstone without and sort of rubberbanding at all. Walked near walls too and was just fine. Even through in a mix of stairs and slabs just for the fun of it and still had no movement problems at all.
> 
> Most likely this is due to an anticheat. Could you please test this without one and report back here with the results? Thanks.

I did some test with the latest enventory branch and I found that all the problem occour when floodgate is enabled, although this sounds wired but I think this is a floodgate problem, also floodgate cause players to disconnect often from the server

**Comment by RednedEpic** [comment]
> I did some test with the latest enventory branch and I found that all the problem occour when floodgate is enabled, although this sounds wired but I think this is a floodgate problem, also floodgate cause players to disconnect often from the server

Have you tested without an anticheat though?

**Comment by AnonAlpha** [comment]
> > I did some test with the latest enventory branch and I found that all the problem occour when floodgate is enabled, although this sounds wired but I think this is a floodgate problem, also floodgate cause players to disconnect often from the server
> 
> Have you tested without an anticheat though?

The latest test result is that without any anticheat, If you walk along the z cord you will get lagged back, but if you walk along the x cord nothing will go wrong

**Comment by AnonAlpha** [comment]
@RednedEpic 
I'm really confused, with the same geyser and paper, one map can do it smoothly without rubberbunding, but another map can't, Can this be related to GameRules?
Also when players are lagged back, it looks like they are just walking backwards, with head turning around

**Comment by MrZillaGold** [comment]
It also works Hypixel
https://www.youtube.com/watch?v=KHvZTgFcL6c
![image](https://user-images.githubusercontent.com/42776347/79593397-bb52f700-811e-11ea-9590-a1b50ca0dadf.png)

**Comment by AnonAlpha** [comment]
It is getting weird, for it don't always happen, sometime it happens sometime it don't, when it happen, no console error log either

**Comment by MrZillaGold** [comment]
When stuck in bamboo

![image](https://user-images.githubusercontent.com/42776347/79626809-5fb45800-8176-11ea-9002-2ac8c58841a0.png)

**Comment by RednedEpic** [comment]
> When stuck in bamboo
> 
> ![image](https://user-images.githubusercontent.com/42776347/79626809-5fb45800-8176-11ea-9002-2ac8c58841a0.png)

Could you send the full error?

**Comment by MrZillaGold** [comment]
It full

**Comment by AnonAlpha** [comment]
More clues about this problem
[Video from the player who are lagging](https://streamable.com/6s7mn4)
[Video from another player watching the lagged player](https://streamable.com/310uvi)
It seems the player who are lagging hasn't moved, but they have walking partical animation below them

**Comment by AnonAlpha** [comment]
That problem is realated to the distance toward the central (0,0)
the number is 4096, if you are at a place which z cord is higher than 4096. you will lag back on x cord; if you are at a place which x cord is higher than 4096, you will lag back on z cord
Here's a video to prove that
[Profe](https://discordapp.com/channels/613163671870242838/613169749525790737/702469734586646548)

**Comment by DoctorMacc** [comment]
Normal movement fixed with #204.

**Comment by RednedEpic** [comment]
Stair bug is still present, however this mitigates the overall problem by fixing walking causing the player to get stuck inside of blocks when outside of 4096.

**Comment by RanTDR** [comment]
slabs are also buggy

**Comment by Heath123** [comment]
> When stuck in bamboo
> 
> ![image](https://user-images.githubusercontent.com/42776347/79626809-5fb45800-8176-11ea-9002-2ac8c58841a0.png)

Should this be a separate issue?

**Comment by AnonAlpha** [comment]
> > When stuck in bamboo
> > ![image](https://user-images.githubusercontent.com/42776347/79626809-5fb45800-8176-11ea-9002-2ac8c58841a0.png)
> 
> Should this be a separate issue?

Yes This should be, it's like non-full block problem

**Comment by RednedEpic** [comment]
From #401, when falling on carpets which have a slime block under them, players will take damage.

**Comment by RednedEpic** [comment]
From #460, anticheats appear to commonly flag Bedrock clients for moving too fast.

**Comment by Heath123** [comment]
@SinonGame Is this fixed by https://github.com/GeyserMC/Geyser/pull/699?

**Comment by MetallicGoat** [comment]
Just wondering if this issue has been fixed yet. I am still getting it today with 1.16.100. This issue is "closed", does that mean it has been fixed, and something else is causing my issue?

**Comment by DoctorMacc** [comment]
It is supposed to be fix. Is `cache-chunks` enabled in your config.

**Comment by MetallicGoat** [comment]
@DoctorMacc No, cache chucks is disabled. Should I enable it?

**Comment by DoctorMacc** [comment]
Yes.

**Comment by MetallicGoat** [comment]
Wow. Works beautify now! Thank you so much. Honestly did not expect that to work. Amazing.

**Comment by DoctorMacc** [comment]
:)

**Comment by SydeVersus** [comment]
The problem still exist in the newest build. No `cache-chunks` exist in the config.
https://dump.geysermc.org/gJG6mbEji44eaReDpBqR8r3eIDO4HSNh

**Comment by Chew** [comment]
Please don't bump year-old issues. Instead, please open a new issue if you're able to reproduce it.

**Comment by Camotoy** [comment]
And please provide as many replication steps as possible.
