### ISSUE TITLE
Banners seem to be Inverted

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#235]
Banners on Bedrock seem to be inverted from how they look in Java

**To Reproduce**
1. Place a banner with a design.
2. View in Java and Bedrock
3. See error

**Expected behavior**
Banners between version should look the same.

**Screenshots**
Java Edition 
![20200322_182317](https://user-images.githubusercontent.com/9083212/77262437-24ecfc00-6c6c-11ea-90ae-a89414c7923d.jpg)

Bedrock Edition
![unknown](https://user-images.githubusercontent.com/9083212/77262438-261e2900-6c6c-11ea-8bb1-fafad231264d.png)

Inverted Bedrock Edition
![unknown-1](https://user-images.githubusercontent.com/9083212/77262616-8745fc80-6c6c-11ea-8432-0c4c765aef65.png)

**Server version**
PaperMC 1.15.2 # 143

**Geyser version**
Inventory branch # 9 standalone

**Bedrock version**
1.14.30

**Comment by Loganh4005** [comment]
must be a mistake in banner colours

**Comment by TheMasterBlaster** [comment]
It does not always seem to be inverted either.

Java
![image](https://user-images.githubusercontent.com/9083212/78705013-cfa32280-78da-11ea-9cae-d308e0c0c80b.png)

Bedrock
![image](https://user-images.githubusercontent.com/9083212/78705029-d893f400-78da-11ea-8700-bff729b769c5.png)

**Comment by rtm516** [comment]
Fixed in inventory branch because of https://github.com/GeyserMC/Geyser/pull/382

**Comment by TheMasterBlaster** [comment]
The Banner that I showed as being purple in bedrock is now green but it still does not look like it does in Java

**Comment by rtm516** [comment]
Mind sharing the banner spawn command if you have it?

**Comment by TheMasterBlaster** [comment]
It was made awhile back in game, after work I can try to remake it online
to get a command

**Comment by rtm516** [comment]
Just tested all banner pattern colours, they work as expected. The issue is that the mappings haven't been updated (there is an open PR) with the banner background colours.

**Comment by rtm516** [comment]
Globe patterns are still broken, as they're not currently available in Bedrock Edition.

**Comment by RednedEpic** [comment]
Fixed in #382.
