### ISSUE TITLE
Console spam with errors

### ISSUE THREAD

**Issue by Dacaly** [GeyserMC/Geyser#2659]
### Describe the bug

The console is being spammed with errors of downstream packet being null and is failing to parse messages.

### To Reproduce

I don't know how to reproduce this bug, it just happens.

### Expected behaviour

No errors and spam in the server console.

### Screenshots / Videos

This spams most of the time:
```
[05:28:44 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:45 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:46 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:46 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:47 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:48 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:48 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:48 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@28c88600, id=2255, owner=com.lahuca.botsentry.bungee.BotSentryBungee@450c57b3, task=com.lahuca.botsentry.b.b.d@63d6898b, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "<local2>" is null
        at com.lahuca.botsentry.b.a.d.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.b.a.d.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.b.a.d.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.b.b.d.run(Unknown Source) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[05:28:49 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:50 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:50 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:51 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:52 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:53 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:53 WARN] [Geyser-BungeeCord]: Downstream packet error! null
[05:28:54 WARN] [Geyser-BungeeCord]: Downstream packet error! null
```

And this sometimes appears:
```
[05:30:56 WARN] [Geyser-BungeeCord]: Failed to parse message
java.lang.NullPointerException: input
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:79) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306) ~[?:?]
        at org.geysermc.geyser.translator.text.MessageTranslator.convertMessage(MessageTranslator.java:107) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.scoreboard.JavaSetPlayerTeamTranslator.translate(JavaSetPlayerTeamTranslator.java:102) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.scoreboard.JavaSetPlayerTeamTranslator.translate(JavaSetPlayerTeamTranslator.java:46) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Server Version and Plugins

```
Server Version: This server is running Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461 by md_5
```
```
Plugins: reconnect_yaml, LuckPerms, VulcanBungee, PremiumVanish, NetworkTools, BungeeGuard, NuVotifier, BungeePluginManager, cmd_list, CleanMOTD, Spicord, Geyser-BungeeCord, MoveMeNow, cmd_find, AdvancedBan, cmd_server, BotSentry, cmd_alert, floodgate, cmd_send, BungeeServerManager
```

### Geyser Dump

https://dump.geysermc.org/hufTTVqnDuM0SUY8YgjjDXAQqOltImcq

### Geyser Version

Geyser version 2.0.0-SNAPSHOT (git-master-3f296e3)

**Comment by Camotoy** [comment]
The bottom error already has an issue. Can you enable debug mode in the Geyser config, restart, and then find these logs again? They will have a full stack trace to go with them.

**Comment by Dacaly** [comment]
```
[06:31:46 WARN] [Geyser-BungeeCord]: Downstream packet error! Index 10 out of bounds for length 10
[06:31:46 ERROR]: java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
[06:31:46 ERROR]:       at com.github.steveice10.mc.protocol.packet.ingame.clientbound.level.ClientboundBlockDestructionPacket.<init>(ClientboundBlockDestructionPacket.java:30)
[06:31:46 ERROR]:       at com.github.steveice10.packetlib.packet.PacketProtocol.createClientboundPacket(PacketProtocol.java:144)
[06:31:46 ERROR]:       at com.github.steveice10.mc.protocol.MinecraftProtocol.createClientboundPacket(MinecraftProtocol.java:180)
[06:31:46 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:59)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[06:31:46 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:31:46 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:31:46 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:31:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:31:46 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[06:31:46 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[06:31:46 ERROR]:       at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[06:31:46 ERROR]:       at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[06:31:46 ERROR]:       at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[06:31:46 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:31:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:31:46 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:31:46 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:31:46 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
```

```
[06:32:05 INFO] [Geyser-BungeeCord]: Team packet  CREATE []
[06:32:05 INFO] [Geyser-BungeeCord]: null
[06:32:05 WARN] [Geyser-BungeeCord]: Failed to parse message
java.lang.NullPointerException: input
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:79) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306) ~[?:?]
        at org.geysermc.geyser.translator.text.MessageTranslator.convertMessage(MessageTranslator.java:107) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.scoreboard.JavaSetPlayerTeamTranslator.translate(JavaSetPlayerTeamTranslator.java:71) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.scoreboard.JavaSetPlayerTeamTranslator.translate(JavaSetPlayerTeamTranslator.java:46) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

```
[06:35:18 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by Snazzy2930
[06:35:18 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=28, stackNetworkId=0) Result: false
[06:35:18 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=194) Result: true
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=224)
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=194)
[06:35:18 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-987, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=28, stackNetworkId=0), destination=StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=194))], filterStrings=[])
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.PlayerInventoryTranslator.translateRequest(PlayerInventoryTranslator.java:225)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:35:18 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:35:18 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:35:18 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:35:18 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:35:18 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[06:35:18 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by Snazzy2930
[06:35:18 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=29, stackNetworkId=0) Result: false
[06:35:18 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=-987) Result: true
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=229)
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=194)
[06:35:18 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-989, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=29, stackNetworkId=0), destination=StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=-987))], filterStrings=[])
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.PlayerInventoryTranslator.translateRequest(PlayerInventoryTranslator.java:225)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:35:18 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:35:18 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:35:18 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:35:18 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:35:18 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[06:35:18 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by Snazzy2930
[06:35:18 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=30, stackNetworkId=0) Result: false
[06:35:18 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=-989) Result: true
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=233)
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=194)
[06:35:18 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-991, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=30, stackNetworkId=0), destination=StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=-989))], filterStrings=[])
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.PlayerInventoryTranslator.translateRequest(PlayerInventoryTranslator.java:225)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:35:18 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:35:18 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:35:18 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:35:18 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:35:18 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[06:35:18 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by Snazzy2930
[06:35:18 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=31, stackNetworkId=0) Result: false
[06:35:18 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=-991) Result: true
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=238)
[06:35:18 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=26, amount=1, nbt=null, netId=194)
[06:35:18 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-993, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=31, stackNetworkId=0), destination=StackRequestSlotInfoData(container=HOTBAR, slot=3, stackNetworkId=-991))], filterStrings=[])
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.PlayerInventoryTranslator.translateRequest(PlayerInventoryTranslator.java:225)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:35:18 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:35:18 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:35:18 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:35:18 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:35:18 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:35:18 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:35:18 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Dacaly** [comment]
The second error regarding team packets seem to be NPC names, but I'm not entirely sure

**Comment by Camotoy** [comment]
The `Index 10 out of bounds for length 10` issue has been fixed.

**Comment by Dacaly** [comment]
Thank for fixing that issue! :D

I do still get this error btw:
```
[06:09:45 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by F1R3M00N
[06:09:45 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=39, stackNetworkId=1406) Result: false
[06:09:45 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR, slot=6, stackNetworkId=1400) Result: true
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=0, amount=0, nbt=null, netId=0)
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=729, amount=4, nbt=null, netId=1400)
[06:09:45 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-279, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=39, stackNetworkId=1406), destination=StackRequestSlotInfoData(container=HOTBAR, slot=6, stackNetworkId=1400))], filterStrings=[])
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:09:45 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:09:45 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:09:45 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:09:45 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:09:45 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[06:09:45 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by F1R3M00N
[06:09:45 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=32, stackNetworkId=1408) Result: false
[06:09:45 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR_AND_INVENTORY, slot=12, stackNetworkId=1394) Result: true
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=0, amount=0, nbt=null, netId=0)
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=692, amount=12, nbt=null, netId=1394)
[06:09:45 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-281, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=32, stackNetworkId=1408), destination=StackRequestSlotInfoData(container=HOTBAR_AND_INVENTORY, slot=12, stackNetworkId=1394))], filterStrings=[])
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:09:45 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:09:45 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:09:45 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:09:45 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:09:45 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[06:09:45 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by F1R3M00N
[06:09:45 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=33, stackNetworkId=1404) Result: false
[06:09:45 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR_AND_INVENTORY, slot=12, stackNetworkId=-281) Result: true
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=0, amount=0, nbt=null, netId=0)
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=692, amount=12, nbt=null, netId=1394)
[06:09:45 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-283, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=33, stackNetworkId=1404), destination=StackRequestSlotInfoData(container=HOTBAR_AND_INVENTORY, slot=12, stackNetworkId=-281))], filterStrings=[])
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:09:45 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:09:45 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:09:45 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:09:45 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:09:45 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[06:09:45 WARN] [Geyser-BungeeCord]: DEBUG: About to reject TAKE/PLACE request made by F1R3M00N
[06:09:45 WARN] [Geyser-BungeeCord]: Source: StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=34, stackNetworkId=1410) Result: false
[06:09:45 WARN] [Geyser-BungeeCord]: Destination: StackRequestSlotInfoData(container=HOTBAR_AND_INVENTORY, slot=12, stackNetworkId=-283) Result: true
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of source slot: GeyserItemStack(javaId=0, amount=0, nbt=null, netId=0)
[06:09:45 WARN] [Geyser-BungeeCord]: Geyser's record of destination slot: GeyserItemStack(javaId=692, amount=12, nbt=null, netId=1394)
[06:09:45 ERROR]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-285, actions=[PlaceStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=CRAFTING_INPUT, slot=34, stackNetworkId=1410), destination=StackRequestSlotInfoData(container=HOTBAR_AND_INVENTORY, slot=12, stackNetworkId=-283))], filterStrings=[])
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:765)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:754)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequest(InventoryTranslator.java:209)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:169)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[06:09:45 ERROR]:       at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[06:09:45 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[06:09:45 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[06:09:45 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[06:09:45 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:09:45 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:09:45 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Dacaly** [comment]
Alright I did. I still get this error

```
[11:09:57 WARN] [Geyser-BungeeCord]: Failed to parse message
java.lang.NullPointerException: input
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:79) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75) ~[?:?]
        at org.geysermc.geyser.platform.bungeecord.shaded.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306) ~[?:?]
        at org.geysermc.geyser.translator.text.MessageTranslator.convertMessage(MessageTranslator.java:107) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.scoreboard.JavaSetPlayerTeamTranslator.translate(JavaSetPlayerTeamTranslator.java:102) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.scoreboard.JavaSetPlayerTeamTranslator.translate(JavaSetPlayerTeamTranslator.java:46) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Camotoy** [comment]
That error is documented in #2606 - though if you're able to figure out which plugin is causing that, we can look into fixing it! If `Downstream packet error! null` has stopped occurring, we can close this specific issue.

**Comment by Dacaly** [comment]
Is it something with nametags? The error seems to be something related to scoreboard teams. Maybe Citizens NPC?

**Comment by Dacaly** [comment]
Weird, seems like the error occurs when a bedrock player disconnects.

**Comment by Dacaly** [comment]
```
[12:18:58] [Netty Worker IO Thread #0/INFO]: [_robingames13|/ip:0] <-> ServerConnector [lobby] has disconnected
[12:19:18] [Network Listener - #1/INFO] [Geyser-BungeeCord]: /ip:57769 tried to connect!
[12:19:19] [Network Listener - #0/INFO] [Geyser-BungeeCord]: Player connected with username robingames13
[12:19:19] [defaultEventLoopGroup-4-2/INFO] [Geyser-BungeeCord]: robingames13 (logged in as: robingames13) has connected to the Java server
[12:19:19] [Netty Worker IO Thread #1/INFO] [floodgate]: Floodgate player logged in as _robingames13 joined (UUID: 00000000-0000-0000-0009-01fbfd1597fc)
[12:19:34] [Netty Worker IO Thread #1/INFO]: [/ip:0|_robingames13] <-> DownstreamBridge <-> [lobby] has disconnected
[12:19:35] [Geyser player thread-3-2/WARN] [Geyser-BungeeCord]: Failed to parse message
java.lang.NullPointerException: input
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
```

**Comment by Camotoy** [comment]
It indeed may be related to name tags.

**Comment by Camotoy** [comment]
The original error message has been resolved here, and I've seen no more reports of it on up-to-date installations, so I will close. Thank you!
