### ISSUE TITLE
Drop items

### ISSUE THREAD

**Issue by alexey267** [GeyserMC/Geyser#2678]
### Describe the bug

Sometimes when a Bedrock player throws an item, it is not thrown away, but simply becomes invisible until "until you open the chest / put it in that place."  If you throw things through the inventory, then there is no problem.
Sorry my English very bad(

### To Reproduce

1) Drop items
2) Items invisibility
3) open chest
4) items no invisibility

### Expected behaviour

Work

### Server Version and Plugins

Last version (Aternos)

### Geyser Version

Last version

### Minecraft: Bedrock Edition Version

1.17.41.01 - 1.18.0.02

**Comment by Konicai** [comment]
Please provide a geyser dump by running `/geyser dump` as asked in the issue template, and a video reproducing the issue if possible

**Comment by vent1998** [comment]
i also have this issue if I try to drop something from the hotbar it goes invisible until it updates

**Comment by timr2000** [comment]
Same issue here ^^, but it seems like i cant find much information about this.

**Comment by Konicai** [comment]
Without more information, the chance that this issue is solved any time soon drops. If you experience this issue, please consider providing a geyser dump as described above.

**Comment by vent1998** [comment]
i know i'm not the original poster but here is my dump since I also have this issue https://dump.geysermc.org/FocH3AQKddZxHN3W251VFoaMh6iXIYlc

**Comment by Camotoy** [comment]
For anyone still experiencing this error, please try the latest Geyser build.

**Comment by Jens-Co** [comment]
Since there was no response for a long time I'll close this issue, if you still are having problems lmk and I'll reopen this.
