### ISSUE TITLE
Stonecutters are unusable since 1.18.30

### ISSUE THREAD

**Issue by spikehidden** [GeyserMC/Geyser#2953]
### Describe the bug

You cannot use stonecutters.

### To Reproduce

1. Join the Server via Bedrock Edition.
2. Click on a stonecutter.
3. Try to craft anything.
4. Items aren't used and you don't get the result item.

### Expected behaviour

You should be able to use stonecutters.

#### Nintendo Switch - Survival Mode

https://user-images.githubusercontent.com/31257733/164998156-8a2abf5b-b9f7-4b1b-a03f-a5c4be88b575.mp4

#### Windows 11 - Creative Mode

https://user-images.githubusercontent.com/31257733/164998704-fbba14b2-5bf2-4b96-9292-2526bea02168.mp4

#### Exact Output of /version
```txt
[00:07:39 INFO]: This server is running Paper version git-Paper-290 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: af94364)
You are 21 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-264 (MC: 1.18.2)
```

#### Plugins:
BedrockPlayerManager
ClaimChunk
DiscordSRV
DropEdit2
dynmap
Dynmap-ClaimChunk*
Dynmap-WorldGuard*
Essentials
EssentialsChat
EssentialsSpawn
floodgate
Geyser-Spigot
GeyserHacks
GeyserSkinManager
Gringotts
HeadDrops
JShader
LuckPerms
MultiLang
MyCommand
Pl-Hide-Pro
PlaceholderAPI
PowerBoard
ProtocolLib
RocketPlaceholders
StreamingDrops
Vault
WorldEdit
WorldGuard

### Geyser Version

2.1.0-SNAPSHOT (git-local/dev-812b2cf)

### Minecraft: Bedrock Edition Device/Version

1.18.30 - Nintendo Switch & Windows 11

### Additional Context

I don't use the main branch as I need the custom item mapping feature. => #2822

That's probably also the reason why the `/geyser dump` command doesn't work.

**Comment by Camotoy** [comment]
Please try updating the extensions branch - this is fixed on master and should be fixed on extensions.

**Comment by spikehidden** [comment]
> Please try updating the extensions branch - this is fixed on master and should be fixed on extensions.

I have but the issue persists. I guess the branch isn't updated and I have to wait.
