### ISSUE TITLE
Totems of Undying makes player unable to break blocks [1.12 Spigot]

### ISSUE THREAD

**Issue by Wiiucoop** [GeyserMC/Geyser#2957]
### Describe the bug

Totems of Undying causes player movement to glitch out and also not able to break any blocks unless they either rejoin server or respawn.

### To Reproduce

1. Get a totem of undying
2. Use the Totem itself
3. Glitch happens

### Expected behaviour

Player should be able to break blocks normally and should not glitch when walking over any walls

### Screenshots / Videos

https://youtu.be/xwG_eiYH1Bc

### Server Version and Plugins

git-Paper-284 (MC:1.18.2)

### Geyser Dump

https://dump.geysermc.org/RoRzPXqplExVODE8SWt26pZqrBXFeNkI

### Geyser Version

2.0.3-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.18.31, Windows

**Comment by Camotoy** [comment]
Please try the latest Geyser version - it's likely this bug is fixed. Thanks!

**Comment by Wiiucoop** [comment]
> Please try the latest Geyser version - it's likely this bug is fixed. Thanks!

I have tried it and it indeed worked just fine on Spigot+PAPER 1.18.2  &   PAPER 1.12.2

However, when I tried this on regular Spigot 1.12.2 (git-Spigot-79a30d7-f4830a1) **the same issue still occurs.**

https://dump.geysermc.org/S7VeZDGHaDh5YEMzxrlzNR75TT4Oy0oB

The only plugins are ViaVersion, GeyserMC, Floodgate
