### ISSUE TITLE
BattlePass Rewards Menu Does NOT SHOW on Bedrock 

### ISSUE THREAD

**Issue by el211** [GeyserMC/Geyser#3266]
### Describe the bug

I have battlepass plugin form GC on spigot
i open the menu works rewards menu shows up on java 
But on Bedrock Rewards menu shows empty !
![image](https://user-images.githubusercontent.com/86126606/188304133-032ef483-be1b-4b73-9536-52a721cd8d6d.png)
here is the 2 pictures showing difference between java and bedrock

NOTE: I AM USING EXTENSION BRANCH OF GEYSER SUPPORTING CUSOTM MODEL DATA

### To Reproduce

1 - download Battlepass plugin
2 - do /pass 
3- click on rewards section
4 on jave you will see everything while on bedrock u see nothing 

I AM USING EXTENSION BRANCH OF GEYSER SUPPORTING CUSOTM MODEL DATA

### Expected behaviour

Well i expected to show the menu 

### Screenshots / Videos

https://user-images.githubusercontent.com/86126606/188304133-032ef483-be1b-4b73-9536-52a721cd8d6d.png

### Server Version and Plugins

[10:17:01 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### Geyser Version

Geyser-BungeeCord version 2.1.0-SNAPSHOT

**Comment by Chew** [comment]
> NOTE: I AM USING EXTENSION BRANCH OF GEYSER SUPPORTING CUSOTM MODEL DATA

Can you try latest master, just in case?

**Comment by Agaloth** [comment]
It works fine for me w/ custom model data support as well (extension branch)
![image](https://user-images.githubusercontent.com/33335971/191666837-1a4e14aa-5103-4ca6-a965-ee7c4343c2e1.png)

**Comment by Camotoy** [comment]
Since we fixed a bug in master that lines up with this bug around the same time, I'll assume it's no longer an issue. Let us know otherwise.

**Comment by el211** [comment]
> Since we fixed a bug in master that lines up with this bug around the same time, I'll assume it's no longer an issue. Let us know otherwise.
its still not working..
![image](https://user-images.githubusercontent.com/86126606/191829211-861eb4d9-5947-43b0-9b55-226a7a3a4b9b.png)

**Comment by Camotoy** [comment]
Can you send a new Geyser dump?

**Comment by el211** [comment]
> Can you send a new Geyser dump?

https://dump.geysermc.org/KA3wX31ea8PEMPLX5PPu5NiG4IB0i8d2

**Comment by Camotoy** [comment]
Can you try with the latest master version too, just in case? (It now has extensions merged in)

**Comment by el211** [comment]
> Can you try with the latest master version too, just in case? (It now has extensions merged in)

same thing

**Comment by el211** [comment]
> Can you try with the latest master version too, just in case? (It now has extensions merged in)

@Camotoy i think we have to reopen this , cz its still not working

**Comment by el211** [comment]
@Camotoy

**Comment by el211** [comment]
**UPDATE**
Same issue goes for the boosters plugin  on spigot

**Comment by onebeastchris** [comment]
Still an issue?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
