### ISSUE TITLE
Minecraft Bedrock players experiencing lag

### ISSUE THREAD

**Issue by LemonBOT8** [GeyserMC/Geyser#3647]
### Describe the bug

Players using Minecraft Bedrock when opening an Inventory or Box will not be able to open it and will see other players warp. very delayed This problem will only occur with Minecraft Bedrock, Minecraft Java in normal server, everything is fine.
( it think it's caused by high latency )

### To Reproduce

Opened the server and encountered this problem.

### Expected behaviour

Delays come and go, looping.

### Screenshots / Videos

https://drive.google.com/file/d/1gYxtWf68iGCKTIvKvt5DbkS5yEUKWKQg/view?usp=sharing

### Server Version and Plugins

Paper-468 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9087a64)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-448 (MC: 1.19.3)

### Geyser Dump

https://dump.geysermc.org/lBLJZogx0fvgXemChFSFpUzWN0D8BYTT

### Geyser Version

Geyser-Spigot version 2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.70

**Comment by Kas-tle** [comment]
You have quite a few plugins here. It would be helpful to narrow down which one specifically is causing the issue.

**Comment by DaddyRobLIVE** [comment]
same issue here, this has been happening ever since the 1.19.70+ release. Bedrock users have been lagging for 2 weeks now :/

**Comment by onebeastchris** [comment]
Please provide geyser dumps and server logs - just bumping the issue won't really help; since there is currently no way to tell if all of you even have the same cause. A geyser dump, server & client version, and logs sent via mclo.gs will help greatly narrowing a potential cause down

**Comment by LemonBOT8** [comment]
Server Log : https://mclo.gs/GZJzh4H

**Comment by HPFeathersen** [comment]
https://dump.geysermc.org/XsIgTvLm1jUr6KLkE6iqfT481C6z19ZE

Here is a geyser dump you can use for reference!

**Comment by ANineonGithub** [comment]
We have the same problem. My sister, cousin, and I have tried to play Bedrock with different Wi-Fi connections, our Mobile network, and even ethernet, but the same problem persists. We tried to play with PlayStation 4 that my cousin plays with, along with our mobile devices, but we still experience this issue. However, this problem does not occur in Java. (I usually use my computer to join the server, but I used my phone to diagnose this issue after my sister and cousin said they were experiencing lag on Bedrock.) After seeing this thread, I think it's not a problem with my server. It would be cool to see this issue fixed.
Dump if needed: https://dump.geysermc.org/NLit2oXGx4FRkGKKR5N7fwrQoi7lZIj6

**Comment by LemonBOT8** [comment]
Additional information video
https://user-images.githubusercontent.com/71535290/228887899-4f44c431-e087-45e3-9b64-8a4a5af7f455.mp4

**Comment by DaddyRobLIVE** [comment]
Yes! This is fixed on the latest version

**Comment by Monkiesh** [comment]
I might have the same issue, but not fixed on the latest version.
Everything works fine at first each time I restart the server. But the lag increases as time goes by. Bedrock players cannot even connect to the server after around an hour, while java players never experience this.
I am running my server on ubuntu 22.04.2 LTS, with a aarch64 cpu.
only geyser was installled, no other plugins or mods.
here is the dump file might of some help: https://dump.geysermc.org/HK44AOnLnxrAhaQ9EkhKi2RCyf54UHeS

**Comment by Camotoy** [comment]
@Monkiesh please make a new issue for this, and try using the Spark plugin to give us some insight.

Spark is a plugin that helps you monitor performance for you server.
https://spark.lucko.me/download

To record performance on your server use:
`/spark profiler --thread * --timeout 60``. This will run for 60 seconds then it will automatically stop.
It'll give us a link we might be able to process.

I'd also try using Paper instead of Spigot, and also try getting a heap dump.

Do note that we will support AArch64, but our resources for debugging on this platform are limited.

**Comment by onebeastchris** [comment]
Closing due to no response. Please provide the info here to re-open the issue.
