### ISSUE TITLE
Player get ReadTimeOut on BungeeCord

### ISSUE THREAD

**Issue by SinonGame** [GeyserMC/Geyser#469]
**Describe the bug**

When using Geyser on BungeeCord, player sometime get `ReadTimeoutException:null`, and they keep getting that error, which makes them unjoinable
**To Reproduce**
1. Set up Geyser on Bungeecord
2. Make lots of player join
3. May see the error

**Expected behavior**

Players can join normally
**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/55188112/80850595-4e2b7f80-8c4f-11ea-9ec3-50ca3f0eb5c4.png)
**Server Version**

BungeeCord latest, paper latest
**Geyser Version**

master build 103
**Minecraft: Bedrock Edition Version**

1.14.6 latest
**Additional Context**

**Comment by AnonAlpha** [comment]
If a player died then log out before they respawn, then the server unload the chunk they are in, they won't be able to join if there's no one in that chunk, only getting this error, it seems geyser won't load the chunk if player isn't alive

**Comment by AnonAlpha** [comment]
[joinrespawn.zip](https://github.com/GeyserMC/Geyser/files/4570898/joinrespawn.zip)
Here's a quick fix plugin for the problem

**Comment by SlickJava** [comment]
can confirm this happens exactly as said on my server as well

**Comment by DoctorMacc** [comment]
Can you confirm if this happens with the Ping Passthrough Rewrite PR?

**Comment by AnonAlpha** [comment]
Don't think this is caused by the ping pass through, it's caused because dead players don't load chunks

**Comment by SlickJava** [comment]
can confirm ping passthrough is unrelated to this, happens with it disabled.

**Comment by DoctorMacc** [comment]
Thank you for testing.

**Comment by AnonAlpha** [comment]
[joinrespawn.zip](https://github.com/GeyserMC/Geyser/files/4591159/joinrespawn.zip)
Here's the source code of the fix plugin I wrote

**Comment by rcmaehl** [comment]
Have this issue.

1. Join bungee server
2. Idle
3. ReadTimeoutException: null after ~60 seconds

**Comment by AnonAlpha** [comment]
> Have this issue.
> 
> 1. Join bungee server
> 2. Idle
> 3. ReadTimeoutException: null after ~60 seconds

Check if my plugin fix the problem

**Comment by toinouH** [comment]
@SinonGame @rcmaehl @SlickJava Does this bug still exist?

**Comment by SinonGame** [comment]
I'm unable to reproduce the problem, but this maybe need to look into. I wasn't able to find the cause of it.

**Comment by rcmaehl** [comment]
@toinouH Will do some testing shortly

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/89082045-e8888580-d35a-11ea-9954-bab4c44ead27.png)

It is significantly better but still an issue

**Comment by DoctorMacc** [comment]
If this issue still persists, how can we reproduce it?

**Comment by anthr76** [comment]
I'm having this issue on waterfall with paper servers

**Comment by rcmaehl** [comment]
I'm also running bungeecord servers where the players are having this issue

**Comment by DoctorMacc** [comment]
@rcmaehl can you attach a Geyser dump? This can be done with `/geyser dump`.

**Comment by anthr76** [comment]
My issue was resolved, by rolling back SkinRestorer

**Comment by rcmaehl** [comment]
> @rcmaehl can you attach a Geyser dump? This can be done with `/geyser dump`.

After a timeout or just any time in general?

**Comment by DoctorMacc** [comment]
Any time - there is no time-specific information we get from the dump.

**Comment by rcmaehl** [comment]
https://dump.geysermc.org/hA1DdRncCF9Dub2HFAi5IVFdUC8neAQv

**Comment by rcmaehl** [comment]
Continuing from discord....

Slingshot doesn't seem to be the full cause but might be part of it. With slingshot enabled, I get the error after ~1.5 minutes. Without it, ~3.5 minutes.

> 04:15:46 [INFO] [Geyser-BungeeCord] /IP:49504 tried to connect!
> 04:15:47 [INFO] [Geyser-BungeeCord] Player connected with username rcmaehl2499
> 04:15:52 [INFO] [Geyser-BungeeCord] Attempting to login using floodgate mode... authentication will be encrypted.
> 04:15:52 [INFO] [Geyser-BungeeCord] Loaded Floodgate key!
> 04:15:52 [INFO] [Geyser-BungeeCord] rcmaehl2499 (logged in as: rcmaehl2499) has connected to remote java server on address 172.18.0.12
> 04:15:52 [INFO] [rcmaehl2499,/172.18.0.12:58380] <-> InitialHandler has connected
> 04:15:52 [INFO] [Geyser-BungeeCord] Registering bedrock skin for [B]rcmaehl2499 (00000000-0000-0000-0009-01f8fdbf6fa1)
> 04:15:52 [INFO] [Geyser-BungeeCord] Unable to load bedrock skin for '[B]rcmaehl2499' as they are likely using a customised skin
> 04:15:52 [INFO] [[B]rcmaehl2499] <-> ServerConnector [hub] has connected
> 04:15:54 [INFO] [Geyser-BungeeCord] Spawned player at -198.966 65 147.78
> 04:19:22 [WARNING] [[B]rcmaehl2499] -> UpstreamBridge - read timed out
> 04:19:22 [INFO] [Geyser-BungeeCord] rcmaehl2499 has disconnected from remote Java server on address 172.18.0.12 because of ReadTimeoutException : null
> 04:19:22 [INFO] [[B]rcmaehl2499] disconnected with: ReadTimeoutException : null
> 04:19:22 [INFO] [[B]rcmaehl2499] -> UpstreamBridge has disconnected
> 04:19:22 [INFO] [[B]rcmaehl2499] <-> DownstreamBridge <-> [hub] has disconnected
> 04:19:22 [INFO] [Geyser-BungeeCord] Bedrock user with ip: /IP has disconnected for reason CLOSED_BY_REMOTE_PEER

Enabling all my bungee plugins brings it back down to about ~60 seconds.

**Comment by toinouH** [comment]
@rcmaehl Can you give the list of the other plugins on bungeecord and the version of bungeecord and maybe (idk if it's usefull or not) but can you give us the name of your server software (the version too) with the plugins ?
If you want you can enable the debug mode in the geyser config.
Have a nice day.

**Comment by RednedEpic** [comment]
Is this still an issue?

**Comment by ExusiaiMoe** [comment]
Seems it has been fixed

**Comment by Camotoy** [comment]
Let us know if this still occurs for anyone else!

**Comment by dayofpay** [comment]
i still have this problem "disconnected with: ReadTimeoutException : null"

**Comment by ZZZZ-afk** [comment]
I am also facing this issue on my server - "disconnected with: ReadTimeoutException : null"

On my server 3-4 people facing now out of 50

**Comment by MrDeathMatch** [comment]
Im also getting this error, please fix

**Comment by liquidman228** [comment]
Same here. Getting this error after like ~3 hours after restart of my survival server. Then players just cannot join it from the lobby. The only (temporary) solution is to just restart that survival server
