### ISSUE TITLE
Recalculating position too often

### ISSUE THREAD

**Issue by Malfrador** [GeyserMC/Geyser#52]
**Describe the bug**
Geyser is trying to recalculate the position of the player while the player is joining and was flying before.
Seemingly it tries to get the player one block down at a time until he is at z: 64 and then up again to ground level.

**To Reproduce**
1. Log in and fly a bit above the ground
2. Log out
3. Log in again
4. Geyser CPU usage spikes to 100%, player gets teleported down slowly

**Expected behavior**
Instant teleported to ground, no teleport at all when player is in creative mode or flying.

**Server version**
1.14.4 Paper

**Geyser version**
Not yet

**Bedrock version**
The current version, 1.12 I guess?

**Additional context**
Maybe a config option to disable the movement check is enough, like the Java server has it.

**Comment by RednedEpic** [comment]
Are you using Tim’s PR version or just the one off Jenkins?

**Comment by Malfrador** [comment]
The one off jenkins, gonna try Tims version now

**Comment by Malfrador** [comment]
Same Issue. And now chunks no longer load (but I have a working bossbar, so that is a plus :D)
`Malfrador moved too quickly. current position: (-28.374714, 102.34002, 302.2285), new position: (0.0, 69.0, 0.0)
Recalculating position...`
~25+ times when joining

**Comment by Tim203** [comment]
That is because we now wait for the client to be ready.
And I'll probably look into a fix for that

**Comment by Tim203** [comment]
I pushed a new commit a few seconds ago, can you try if the moved too quickly is reduced now?

**Comment by Malfrador** [comment]
> I pushed a new commit a few seconds ago, can you try if the moved too quickly is reduced now?
Sadly not, same issue still. Its sometimes even worse, up to 100 movement checks with Geyser freezing/crashing

Joining the server sometimes "fixes" it, but sometimes even in spectator mode the same thing happens.
I also now sometimes have the issue that I join the server via Geyser and then im stuck, can't move, open the chat or use the escape menu. 

I tried using an 1.13.2 server + ViaVersion. This worked quite well and the movement checks were the only issue.

I then tried an 1.14.4 server to rule out any issues that might be caused by ViaVersion, which resulted in a Geyser CPU usage of 95%  when joining and the minecraft server crashing as a result of this. 
The high CPU usage seems to be a result of the movement checks, as it was showing this in the powershell console very slowly (like one check every 30s).

I guess an option to disable this "feature" is probably best for now. The Minecraft server does movement checks on its own and kicks a player for invalid movement, so why do it on geyser again?

**Comment by Tim203** [comment]
I thought it had to do with the server (Spigot).
Amd are you sure you're using the latest commit of my pr? I really thought that will fix it.

**Comment by Malfrador** [comment]
I'm really sure that I had the correct PR. 
I only tested 1.14.4 once (and only had this spike once) because it was really annoying with the high CPU usage. I might try it again and see if it's related to something else (flying, missing chunks etc)

**Comment by Tim203** [comment]
I almost know for sure that it has to do with the 'waiting for client feature'

**Comment by EOT3000** [comment]
confirmed bug

**Comment by Tim203** [comment]
Has it been fixed? I accidentally pushed something (around half an hour ago) that should probably fix it

**Comment by Malfrador** [comment]
I did 5 Logins. I logged in, walked a few blocks and logged out again. Then I repeated the process.
In 2/5 cases, the issue appeared again, but Geyser only did two movement checks instead of 50+. Definitely better. 3 of the logins worked without any movement check.

CPU usage is still extremely high when logging in.

**Comment by EOT3000** [comment]
note to all devs, should probably make timings, for debug purposes

**Comment by Tim203** [comment]
The 65 is normal. It is (ViaVersions) 64 radius + 1 :p
And I'm not sure what causes the CPU to spike

**Comment by EOT3000** [comment]
try running a profiler

**Comment by Malfrador** [comment]
Any profiler you could recommend? Im not a java dev :D

**Comment by EOT3000** [comment]
jprofiler, came up with a google search

**Comment by EOT3000** [comment]
https://www.ej-technologies.com/products/jprofiler/overview.html

**Comment by EOT3000** [comment]
@Malfrador any updates?

**Comment by Malfrador** [comment]
Still downloading, Slow german internet, will take a few minutes ^^

**Comment by Malfrador** [comment]
![jprofiler_2019-10-09_22-05-40](https://user-images.githubusercontent.com/6106558/66516452-52405600-eae1-11e9-88d8-800b18ef6512.png)
Seems like converting Chunks is the big issue.

**Comment by EOT3000** [comment]
very useful!

**Comment by RednedEpic** [comment]
I’m rewriting the remapper, which _should_ resolve this issue when complete.

**Comment by EOT3000** [comment]
Closing due to the new issue

**Comment by Tim203** [comment]
#58
