### ISSUE TITLE
Area Effect Cloud radius is not applied correctly

### ISSUE THREAD

**Issue by nicolube** [GeyserMC/Geyser#5219]
### Describe the bug

I try to summon an invisble area effect cloud with an radius of 0  (We use them for custom hitboxes).

In Java, the Area Effet Cloud particles are invisible. But in bedrock it shows up...

### To Reproduce

1. Execute: `/summon area_effect_cloud ~ ~ ~ {Radius:0,Duration:200}`

### Expected behaviour

No Particles should spawn in bedrock.

### Server Version and Plugins

This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-132-b48403b (MC: 1.21.1)

### Geyser Dump

-

### Geyser Version

Geyser version 2.6.0-b730 (git-master-ba5b422)

### Minecraft: Bedrock Edition Device/Version

1.21.44, Windows Edition

**Comment by onebeastchris** [comment]
thanks for the reproduction steps! fixed in https://github.com/GeyserMC/Geyser/commit/a7d475e7e45189d7448d4324b80e91cb2d39df40

**Comment by nicolube** [comment]
@onebeastchris I still see black partickes when spawning them like this...

`/summon area_effect_cloud ~ ~ ~ {Radius:0,Duration:200}`

**Comment by onebeastchris** [comment]
Please add further info - what platforms is this still occurring on? Is this tested with a server with no other plugins?

I'm not able to reproduce this issue after the linked fix

**Comment by CrazyDev05** [comment]
i can reproduce it on client `v1.21.51` and geyser `2.6.0-b750 (git-master-98f9bf6)`

**Comment by onebeastchris** [comment]
Which Bedrock platform? Win 10/11? 
Bedrock can be quite weird with how it behaves differently based on platforms.

Further, knowing which Java server platform & version this occurs with would also help in reproducing the issue. Thanks!

**Comment by CrazyDev05** [comment]
windows 11
The server structure is as following: Geyser Standalone -> Velocity 3.4.0-SNAPSHOT (git-965db127-b454) -> Paper 1.21.3-81-master@da71382

**Comment by ByteExceptionM** [comment]
I still have the same issue on Win 10/11 Edition. Running on [98f9bf6](https://github.com/GeyserMC/Geyser/commit/98f9bf6b6281a268e9ae1ac1eccb2c4a10dfebde)

**Comment by Tjorven-Liebe** [comment]
this is still an issue
