### ISSUE TITLE
Inventory Bugs

### ISSUE THREAD

**Issue by forsakenliquid** [GeyserMC/Geyser#5437]
### Describe the bug

Inventorys not loading

### To Reproduce

join firstmc.de
join citybuild
use command /wand on a plot

### Expected behaviour

A inventory opens after you click the item in the Video. It all works on Java & Bedrock(PC only) perfectly fine.

https://youtu.be/Az69uZMsOow -> Expected behaviour

### Screenshots / Videos

https://www.youtube.com/watch?v=3wyjR_2BApc -> this is the problem 

### Server Version and Plugins

Minecraft Version 1.21.4
Purpur Server
Velocity Proxy

### Geyser Dump

https://dump.geysermc.org/Nu02k77FnyDA2iEY7nOsOlJmrIpdz26y

### Geyser Version

8cf6581 · latest

### Minecraft: Bedrock Edition Device/Version

1.21.70

### Additional Context

feel free to add me on Discord if you need any additional informations (liquid361)

**Comment by onebeastchris** [comment]
Fixed with https://github.com/GeyserMC/Geyser/commit/baac9795b74d339604a4b5613cae5820885c3350

**Comment by forsakenliquid** [comment]
No not for me

**Comment by forsakenliquid** [comment]
https://github.com/user-attachments/assets/24337bfd-1f99-4dfb-b514-a75615a5988d

**Comment by Dxzo** [comment]
same here, for lands plugin menu still persist

**Comment by Kas-tle** [comment]
Reported with this plugin in Discord: https://github.com/GeorgH93/Minepacks

**Comment by Saintdane91** [comment]
Had my own post up, was sent here :) currently /jobs browse and /backpack not working, so ya its just certain inventory type menus are working and others are not

**Comment by Mark-Kincaid** [comment]
> Had my own post up, was sent here :) currently /jobs browse and /backpack not working, so ya its just certain inventory type menus are working and others are not

same here with an inventory style panel from CommandPanels. Throws [THIS ERROR](https://mclo.gs/XFM2dcI)

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/pull/5443 should resolve this issue. Please test the builds linked in the PR

**Comment by forsakenliquid** [comment]
[latest.log](https://github.com/user-attachments/files/19524538/latest.log)

Got some errors

**Comment by forsakenliquid** [comment]
Got some reports that the bug still persists and players cant open some Inventorys. Im sorry to tell you that :C

https://github.com/user-attachments/assets/0e80d20e-46d6-4433-89ae-e7206d06697c

**Comment by onebeastchris** [comment]
try re-downloading the build on the PR, might just resource this

**Comment by forsakenliquid** [comment]
[14:09:13 ERROR] [geyser]: Could not translate packet ClientboundContainerClosePacket
java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @7ac9af2a)
        at org.geysermc.geyser.translator.inventory.chest.SingleChestInventoryTranslator.closeInventory(SingleChestInventoryTranslator.java:71) ~[?:?]
        at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:176) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:43) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:35) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:92) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:70) ~[?:?]
        at org.geysermc.geyser.session.GeyserSessionAdapter.packetReceived(GeyserSessionAdapter.java:227) ~[?:?]
        at org.geysermc.mcprotocollib.network.session.NetworkSession.callPacketReceived(NetworkSession.java:134) ~[?:?]
        at org.geysermc.mcprotocollib.network.session.NetworkSession.lambda$channelRead0$3(NetworkSession.java:275) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:09:13 ERROR]: java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @7ac9af2a)
[14:09:13 ERROR]:       at org.geysermc.geyser.translator.inventory.chest.SingleChestInventoryTranslator.closeInventory(SingleChestInventoryTranslator.java:71)
[14:09:13 ERROR]:       at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:176)
[14:09:13 ERROR]:       at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:43)
[14:09:13 ERROR]:       at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:35)
[14:09:13 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:92)
[14:09:13 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:70)
[14:09:13 ERROR]:       at org.geysermc.geyser.session.GeyserSessionAdapter.packetReceived(GeyserSessionAdapter.java:227)
[14:09:13 ERROR]:       at org.geysermc.mcprotocollib.network.session.NetworkSession.callPacketReceived(NetworkSession.java:134)
[14:09:13 ERROR]:       at org.geysermc.mcprotocollib.network.session.NetworkSession.lambda$channelRead0$3(NetworkSession.java:275)
[14:09:13 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[14:09:13 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[14:09:13 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
[14:09:13 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:09:13 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[14:09:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by forsakenliquid** [comment]
although, all inventories working right now.

**Comment by forsakenliquid** [comment]
sometimes the reopening from the plugins dont work, but the opening works fine

https://www.youtube.com/watch?v=Rzt8ijKJeyU

**Comment by forsakenliquid** [comment]
> > [14:09:13 ERROR] [geyser]: Could not translate packet ClientboundContainerClosePacket
> > java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @7ac9af2a)
> > at org.geysermc.geyser.translator.inventory.chest.SingleChestInventoryTranslator.closeInventory(SingleChestInventoryTranslator.java:71) ~[?:?]
> > at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:176) ~[?:?]
> > at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:43) ~[?:?]
> > at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:35) ~[?:?]
> > at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:92) ~[?:?]
> > at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:70) ~[?:?]
> > at org.geysermc.geyser.session.GeyserSessionAdapter.packetReceived(GeyserSessionAdapter.java:227) ~[?:?]
> > at org.geysermc.mcprotocollib.network.session.NetworkSession.callPacketReceived(NetworkSession.java:134) ~[?:?]
> > at org.geysermc.mcprotocollib.network.session.NetworkSession.lambda$channelRead0$3(NetworkSession.java:275) ~[?:?]
> > at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
> > at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
> > at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
> > at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
> > at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-c9aa1cca-b480)]
> > at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> > [14:09:13 ERROR]: java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @7ac9af2a)
> > [14:09:13 ERROR]:       at org.geysermc.geyser.translator.inventory.chest.SingleChestInventoryTranslator.closeInventory(SingleChestInventoryTranslator.java:71)
> > [14:09:13 ERROR]:       at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:176)
> > [14:09:13 ERROR]:       at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:43)
> > [14:09:13 ERROR]:       at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:35)
> > [14:09:13 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:92)
> > [14:09:13 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:70)
> > [14:09:13 ERROR]:       at org.geysermc.geyser.session.GeyserSessionAdapter.packetReceived(GeyserSessionAdapter.java:227)
> > [14:09:13 ERROR]:       at org.geysermc.mcprotocollib.network.session.NetworkSession.callPacketReceived(NetworkSession.java:134)
> > [14:09:13 ERROR]:       at org.geysermc.mcprotocollib.network.session.NetworkSession.lambda$channelRead0$3(NetworkSession.java:275)
> > [14:09:13 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
> > [14:09:13 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
> > [14:09:13 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
> > [14:09:13 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> > [14:09:13 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> > [14:09:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> If you can reproduce this, please provide a full log with geyser's debug mode enabled - otherwise I'll just have to attempt to guess and and safeguards to ensure this doesn't happen

Idk how i got this. It was just after the start and never came back

**Comment by Saintdane91** [comment]
Update from my tests: I re-downloaded/uploaded it again, made sure to refresh the config as well, my bedrock players still coming into issues with /backpack and /jobs browse

![Image](https://github.com/user-attachments/assets/c5562d97-01f5-45a5-b179-1d676e450f1e)

**Comment by onebeastchris** [comment]
@Saintdane91 please provide more info:

    1. Enable debug-mode in the Geyser config.yml, and restart the server
    2. Join the server and play for a while until you (or any user) runs into this issue again
    3. Write a comment here with a geyser dump, and a full server log showing (ideally uploaded via mclo.gs)

**Comment by onebeastchris** [comment]
This should be resolved now in the latest . If it isn't:
- Enable `debug-mode` in the Geyser config.yml, and restart the server
- Join the server and play for a while until you (or any user) runs into this issue again
- Write a comment here with a geyser dump, and a full server log showing (ideally uploaded via mclo.gs)

Thanks!
