### ISSUE TITLE
Strange error during the game

### ISSUE THREAD

**Issue by CuteTadpole** [GeyserMC/Geyser#545]
**Describe the bug**

I'm testing Geyser on the server Emeraldix.net (completely in Russian). So, while I'm playing, I can be kicked from the game because of strange error (see the image)

**To Reproduce**
1. Configure the GeyserMC to remote emeraldix.net:25565
2. Register or login using /reg password or /l password
3. Go straight to the armor stand named "Крипто Полис"
4. Walk for a few minutes
5. You'll get the error

**Expected behavior**

Normal playing on this server

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/61086561/81801051-8028c580-951c-11ea-9efc-51cb0b9d4d00.png)

**Server Version**

All I know is Paper 1.12.2 with ViaVersion 1.15.2 

**Geyser Version**

Geyser version 1.0-SNAPSHOT (git-master-46b0054) Standalone

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

```
[12:53:42 INFO] CuteTadpole6385 has disconnected from remote java server on address emeraldix.net because of io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 10 has no mapping for key class com.github.steveice10.mc.protocol.data.game.world.block.UpdatedTileType.
> io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 10 has no mapping for key class com.github.steveice10.mc.protocol.data.game.world.block.UpdatedTileType.
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:473)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Value 10 has no mapping for key class com.github.steveice10.mc.protocol.data.game.world.block.UpdatedTileType.
        at com.github.steveice10.mc.protocol.data.MagicValues.key(MagicValues.java:1245)
        at com.github.steveice10.mc.protocol.packet.ingame.server.world.ServerUpdateTileEntityPacket.read(ServerUpdateTileEntityPacket.java:32)
        at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
        ... 40 more
```
You can contact the creator of this server in Discord: \_CrazyWords\_#8598

**Comment by rtm516** [comment]
Please come over to our [Discord](http://discord.geysermc.org/), it's likely you just have a corrupt jar.

**Comment by CuteTadpole** [comment]
Sorry, but this error still appears :(

**Comment by DoctorMacc** [comment]
I saw this error once while placing down a shulker box in a 1.12.2 world. Likely a confirmed bug but more research is needed.

**Comment by CuteTadpole** [comment]
I just checked the comment above and placed shulker on the floor and really got this error

**Comment by rtm516** [comment]
This is an issue with the underlying protocol library, I have PRd a fix when its merged this issue should be solved.
https://github.com/Steveice10/MCProtocolLib/pull/538

**Comment by CuteTadpole** [comment]
So I saw that this PR https://github.com/Steveice10/MCProtocolLib/pull/538 was merged, but this bug still happens. What I need to do to solve this bug?

**Comment by rtm516** [comment]
> So I saw that this PR [Steveice10/MCProtocolLib#538](https://github.com/Steveice10/MCProtocolLib/pull/538) was merged, but this bug still happens. What I need to do to solve this bug?

Are you on the latest build of Geyser?

**Comment by CuteTadpole** [comment]
> > So I saw that this PR [Steveice10/MCProtocolLib#538](https://github.com/Steveice10/MCProtocolLib/pull/538) was merged, but this bug still happens. What I need to do to solve this bug?
> 
> Are you on the latest build of Geyser?

Yes, I am

**Comment by rtm516** [comment]
This was only fixed after the last Geyser build, so the next one will have the latest version of https://github.com/Steveice10/MCProtocolLib/ in it.

**Comment by RednedEpic** [comment]
Resolved in latest build.
