### ISSUE TITLE
Could not translate packet ClientboundEntityEventPacket

### ISSUE THREAD

**Issue by RunqRun** [GeyserMC/Geyser#5647]
### Describe the bug

I have been getting this error since around 1.21.90.
I don't know if this error is the cause, but frequently threads are dropping in OOM Killer.
```
[17:30:58.475 Geyser player thread-5-4/ERROR] Could not translate packet ClientboundEntityEventPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.inventory.GeyserItemStack.isEmpty()" because "itemStack" is null
        at org.geysermc.geyser.translator.item.ItemTranslator.getBedrockItemDefinition(ItemTranslator.java:520) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.protocol.java.entity.JavaEntityEventTranslator.translate(JavaEntityEventTranslator.java:107) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.protocol.java.entity.JavaEntityEventTranslator.translate(JavaEntityEventTranslator.java:63) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:92) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:70) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.session.GeyserSessionAdapter.packetReceived(GeyserSessionAdapter.java:227) ~[Geyser-Standalone.jar:?]
        at org.geysermc.mcprotocollib.network.session.NetworkSession.callPacketReceived(NetworkSession.java:144) ~[Geyser-Standalone.jar:?]
        at org.geysermc.mcprotocollib.network.session.NetworkSession.lambda$channelRead0$3(NetworkSession.java:319) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:148) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073) ~[Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
```

### To Reproduce

Start with latest Standalone

### Expected behaviour

I need you to resolve the error.

### Geyser Version

2.8.2-b872 (git-master-74456ee)

**Comment by eclipseisoffline** [comment]
Hi, if you download the latest build once if finishes (within 10-15 minutes or so), this issue should now be fixed!

**Comment by Shortaholic** [comment]
After downloading the new version, Im still getting these errors.

**Comment by onebeastchris** [comment]
Please provide a geyser dump

**Comment by Shortaholic** [comment]
> Please provide a geyser dump

https://mcpaste.io/12cbe48be4ac8a65

**Comment by onebeastchris** [comment]
That's updated, interesting. Is it the exact same stacktrace?

**Comment by Shortaholic** [comment]
> That's updated, interesting. Is it the exact same stacktrace?

I apologise, I read the top error incorrectly but ever since downloading the 1.21.93 update, Ive been getting these errors spammed in Proxy console -- https://mcpaste.io/db3c3b0728586a0c

**Comment by onebeastchris** [comment]
Try re-downloading Geyser-Standalone - I just checked manually, that class should definitely be there, so this could be a corrupted jar?

**Comment by Shortaholic** [comment]
> Try re-downloading Geyser-Standalone - I just checked manually, that class should definitely be there, so this could be a corrupted jar?

Would I not want to download the Geyser-Velocity since its on my Proxy? I dont have a standalone Proxy for bedrock.

Edit: Just tried redownloading the jar and I still have the same issue.

**Comment by onebeastchris** [comment]
Oh right. In that case, you'd want to update velocity - that should resolve this issue

(You're running build 453, latest is 521)

**Comment by Shortaholic** [comment]
> Oh right. In that case, you'd want to update velocity - that should resolve this issue
> 
> (You're running build 453, latest is 521)

Yep, it works now. Thank you so much!
