### ISSUE TITLE
Bedrock user loses all inventory & GUI access after closing Form from Floodgate API

### ISSUE THREAD

**Issue by ptthanh02** [GeyserMC/Geyser#5850]
### Describe the bug

When sending a Bedrock form through the Floodgate API, after the player closes the form (whether they made a selection or not), they can no longer open any inventory (player inventory, chest, furnace, etc.). No errors from console log, the only way to fix it is for the player to rejoin the server.

### To Reproduce

1. Connect to the server with a Bedrock client.
2. Send a Floodgate form to the player via plugin with Floodgate API.
3. The player closes the form (with or without making a choice).
4. Try opening the player inventory, a chest, or any container → nothing opens.

### Expected behaviour

- After closing the form, the player should be able to open their inventory and other containers normally without rejoining.

### Screenshots / Videos

Open a form from Floodgate API:

<img width="1920" height="998" alt="Image" src="https://github.com/user-attachments/assets/fc3e0ee5-2f96-4bc1-9e19-c9b07631c612" />

Try opening a chest after the form closed:

<img width="1920" height="996" alt="Image" src="https://github.com/user-attachments/assets/134febf8-bb02-4ea3-97ce-7a5d8cd41d17" />

The chest stay opened after the player move far away:

<img width="1920" height="994" alt="Image" src="https://github.com/user-attachments/assets/148b5359-75f2-4904-99f1-2182a5e998c9" />

Only open another chest will make it close: (press E to open inventory doesnt work)

<img width="1920" height="993" alt="Image" src="https://github.com/user-attachments/assets/8a59bb15-8e13-48e9-9c7d-6b5c8cbcb851" />
It seems like the server still thinks a GUI is open.

### Server Version and Plugins

- Server: Paper 1.21.8 #Buiild 60 (29c8822 - Remove no longer needed MC-210802 fix (#13059))
- Floodgate API version: org.geysermc.floodgate:api:2.2.4-SNAPSHOT
Plugin list: 
  - floodgate (2.2.4-SNAPSHOT (b118-40d320a)
  - Vault (1.7.3-b131)
  - Geyser-Spigot (2.8.3-SNAPSHOT)
  - Essentials (2.22.0-dev+28-0aa25c8)
  - SmartSpawner (1.5.3)

### Geyser Dump

https://dump.geysermc.org/pUUHvvCPdl3G37b0CryCe0yFDfXo42lJ

### Geyser Version

2.8.3-b939 (git-master-1600ccb)

### Minecraft: Bedrock Edition Device/Version

Minecraft Bedrock version: 1.21.101 (Windows 11))

### Additional Context

- You can view the code for the form here: https://github.com/NighterDevelopment/smartspawner/blob/main/core/src/main/java/github/nighter/smartspawner/spawner/gui/main/SpawnerMenuFormUI.java

**Comment by onebeastchris** [comment]
This should be resolved with https://github.com/GeyserMC/Geyser/commit/a1cb9bdb527fc2f71cdbd949efc12ed1f606bff1

**Comment by Nighterezi** [comment]
Hi @onebeastchris the problem is still occuring for me (with ther lastest version of geyser), here is the geyser dump:
https://dump.geysermc.org/3GYfEc5kNKkbaVzCy1LWj6DMDCYiHqSQ

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/commit/c485b38f20b27c3f36d2702c54c6abf00f7bc75a
This branch (see the action run) should resolve this issue - can you test? 😄

**Comment by AlexMl** [comment]
I don't have this specific problem, but I have a feeling forms open a lot more reliable on this branch.

**Comment by Nighterezi** [comment]
Hi @onebeastchris, thanks for the help! I just realized the issue was on my side. I had coded it to open a Bedrock form but accidentally opened a Java GUI inventory right after. I’ve resolved this now and tested three versions:

* [d2dd949](https://github.com/GeyserMC/Geyser/commit/d2dd949eebfd70fd531a76772fb5c30c5285987c) #5844 (Geyser 2.8.3)
* [a1cb9bd](https://github.com/GeyserMC/Geyser/commit/a1cb9bdb527fc2f71cdbd949efc12ed1f606bff1) #5856 (Geyser 2.8.4)
* [c485b38](https://github.com/GeyserMC/Geyser/commit/c485b38f20b27c3f36d2702c54c6abf00f7bc75a) Yours

All three are working perfectly now. Sorry for the inconvenience! You may rollback the changes for forms if necessary

**Comment by onebeastchris** [comment]
Merged the linked branch - thanks for testing.
