### ISSUE TITLE
Java Heads/NPC Skins no longer showing on bedrock

### ISSUE THREAD

**Issue by owlish489** [GeyserMC/Geyser#6026]
### Describe the bug

Java NPC skins are not loading for Bedrock players since we updated to the new version of Geyser (Build #1002)

Heads are hanging steves with an extra head at the feet

and npc skins are just steve

### To Reproduce

1. download and install Geyser Build 1002 (https://github.com/GeyserMC/Geyser/commit/0cdd31ea1fa4c7881e40a0364e54fb2e558812de)
2. restart server
3. Bedrock player joins
4. Attempt relog
5. Attempt server full reboot
6. Issue still persists

### Expected behaviour

Heads look as they should when placed only
NPCs show respective skins

### Screenshots / Videos

<img width="677" height="297" alt="Image" src="https://github.com/user-attachments/assets/7b10b510-ed8b-4388-b04d-16c2ee3225d3" />

<img width="732" height="323" alt="Image" src="https://github.com/user-attachments/assets/9c3f6efa-9e0d-49e2-972f-cfb672f6afed" />

### Geyser Dump

https://dump.geysermc.org/XOmpCKWwo5C2tyb2iI5rZbI9pOvRPOYy

### Geyser Version

This server is running Geyser version 2.9.1-b1002 (git-master-0cdd31e) (Java: 1.21.9, Bedrock: 1.21.90 - 1.21.130)

### Minecraft: Bedrock Edition Device/Version

Mobile, 1.21.130 automatic update

**Comment by Novampr** [comment]
We're aware of the skin issues, we're looking into it!

**Comment by onebeastchris** [comment]
Fixed with https://github.com/GeyserMC/Geyser/commit/bc8214793ee723c9e75e134baf47cbdcb56c59f5

**Comment by ReyMaicer** [comment]
i have the same problem still, already updated

**Comment by owlish489** [comment]
Updated to 1004.

Heads now work, npc skins still do not.

![Image](https://github.com/user-attachments/assets/5ff9e56c-e946-4c52-8947-53850cca486a)
