### ISSUE TITLE
[1.16] WHITE color in chat

### ISSUE THREAD

**Issue by OverBrave** [GeyserMC/Geyser#912]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47111280/86782305-91e3a080-c067-11ea-98f6-f7275f5e2584.png)

**Server Version**
1.16.1
**Geyser Version**
Build 99

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by rtm516** [comment]
What is meant to be happening here can u give us a comparison with java and explain it?

**Comment by OverBrave** [comment]
Look chat, i only write a but in chat whitewhitea

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/86789960-8fd20f80-c070-11ea-957e-c8128165372c.png)

**Comment by rtm516** [comment]
im unable to replicate this, with both `/tellraw @p {"text":"Test","color":"white"}` and `say §00 §11 §22 §33 §44 §55 §66 §77 §88 §99 §aa §bb §cc §dd §ee §ff`

**Comment by OverBrave** [comment]
In JAVA or bedrock ?

**Comment by rtm516** [comment]
Both
![image](https://user-images.githubusercontent.com/5401186/86791294-4af2ac80-c061-11ea-893a-95e075ffd0c8.png)

**Comment by rtm516** [comment]
It's likely down to an outdated chat plugin.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/86791590-5ef2da00-c072-11ea-9009-e9ff3c9e1f3e.png)
![image](https://user-images.githubusercontent.com/47111280/86792081-cd379c80-c072-11ea-940a-0fe08bac5eb6.png)

I can't send say §00 §11 §22 §33 §44 §55 §66 §77 §88 §99 §aa §bb §cc §dd §ee §ff in bedrock, because said "illegal characters"

I'am using CMI chat feature

**Comment by rtm516** [comment]
Replace the `§` with `&` and try

**Comment by agoniaprivat** [comment]
Happens to me too ^^
It happens when textcolor is set to be white.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/86792331-0c65ed80-c073-11ea-8374-dbdf5b45dbef.png)
And i cant put § on java, if put &
![image](https://user-images.githubusercontent.com/47111280/86792395-1c7dcd00-c073-11ea-8d58-dcdaa4cdccab.png)

in bedrock
![image](https://user-images.githubusercontent.com/47111280/86792567-4e8f2f00-c073-11ea-9846-c0a5b19e75d4.png)

**Comment by rtm516** [comment]
Managed to replicate the issue, looking into it now
Thanks @agoniaprivat

**Comment by rtm516** [comment]
Fixed by https://github.com/GeyserMC/Geyser/commit/a16deb269a1f4553d9277ee998f71be67b89f74a

**Comment by BttrThnCode** [comment]
its not fixed still... I cant use the '§' on bedrock to add color to a chat text.

**Comment by lukeeey** [comment]
Your bedrock player probably doesn’t have permission
